package org.didban.monitor

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.ContentCopy
import androidx.compose.material.icons.rounded.DeleteOutline
import androidx.compose.material.icons.rounded.PlayArrow
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material.icons.rounded.Save
import androidx.compose.material.icons.rounded.Stop
import androidx.compose.material.icons.rounded.Tune
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch

private enum class TunnelConfirmAction {
    DEPLOY,
    START,
    STOP,
    RESTART,
    DELETE
}

@Composable
fun CommandTunnelEditorScreen(
    copy: CommandCopy,
    onBack: () -> Unit
) {
    SecureWindowEffect()
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var records by remember { mutableStateOf(Prefs.loadTunnels(context)) }
    var selectedId by remember { mutableStateOf<Long?>(null) }
    var name by remember { mutableStateOf(copy.tunDefaultName) }
    var coreName by remember { mutableStateOf(TunnelCore.BACKPACK.name) }
    var transportName by remember { mutableStateOf(TunnelTransport.STEALTH.name) }
    var iranHost by remember { mutableStateOf("") }
    var iranPort by remember { mutableStateOf("443") }
    var foreignHost by remember { mutableStateOf("") }
    var foreignPort by remember { mutableStateOf("8443") }
    var corePort by remember { mutableStateOf("3080") }
    var token by remember { mutableStateOf("") }
    var preset by remember { mutableStateOf("turbo") }
    var kcpMode by remember { mutableStateOf("fast") }
    var encryption by remember { mutableStateOf("aes-128-gcm") }
    var spoofSrcIp by remember { mutableStateOf("1.1.1.1") }
    var spoofPeerIp by remember { mutableStateOf("8.8.8.8") }
    var virtualIpIran by remember { mutableStateOf("10.200.200.2") }
    var virtualIpForeign by remember { mutableStateOf("10.200.200.1") }
    var mtu by remember { mutableStateOf("1350") }
    var acceptUdp by remember { mutableStateOf(true) }
    var proxyProtocol by remember { mutableStateOf(false) }
    var wsPath by remember { mutableStateOf("/tunnel") }
    var wsHost by remember { mutableStateOf("") }
    var multiPorts by remember { mutableStateOf("") }
    var autoSync by remember { mutableStateOf(true) }
    var discovered by remember { mutableStateOf(false) }
    var enabled by remember { mutableStateOf(true) }
    var message by remember { mutableStateOf<String?>(null) }
    var error by remember { mutableStateOf<String?>(null) }
    var busy by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf<GeneratedTunnelCode?>(null) }
    var artifact by remember { mutableStateOf("iran-config") }
    var confirmAction by remember { mutableStateOf<TunnelConfirmAction?>(null) }
    var confirmConfig by remember { mutableStateOf<TunnelConfig?>(null) }

    fun resetForm() {
        selectedId = null
        name = copy.tunDefaultName
        coreName = TunnelCore.BACKPACK.name
        transportName = TunnelTransport.STEALTH.name
        iranHost = ""
        iranPort = "443"
        foreignHost = ""
        foreignPort = "8443"
        corePort = "3080"
        token = ""
        preset = "turbo"
        kcpMode = "fast"
        encryption = "aes-128-gcm"
        spoofSrcIp = "1.1.1.1"
        spoofPeerIp = "8.8.8.8"
        virtualIpIran = "10.200.200.2"
        virtualIpForeign = "10.200.200.1"
        mtu = "1350"
        acceptUdp = true
        proxyProtocol = false
        wsPath = "/tunnel"
        wsHost = ""
        multiPorts = ""
        autoSync = true
        discovered = false
        enabled = true
        generated = null
        message = null
        error = null
    }

    fun selectTunnel(cfg: TunnelConfig) {
        selectedId = cfg.id
        name = cfg.name
        coreName = cfg.core.name
        transportName = cfg.transport.name
        iranHost = cfg.iranHost
        iranPort = cfg.iranPort.toString()
        foreignHost = cfg.foreignHost
        foreignPort = cfg.foreignPort.toString()
        corePort = cfg.corePort.toString()
        token = cfg.token
        preset = cfg.preset
        kcpMode = cfg.kcpMode
        encryption = cfg.encryption
        spoofSrcIp = cfg.spoofSrcIp
        spoofPeerIp = cfg.spoofPeerIp
        virtualIpIran = cfg.virtualIpIran
        virtualIpForeign = cfg.virtualIpKharej
        mtu = cfg.mtu.toString()
        acceptUdp = cfg.acceptUdp
        proxyProtocol = cfg.proxyProtocol
        wsPath = cfg.wsPath
        wsHost = cfg.wsHost
        multiPorts = cfg.multiPorts
        autoSync = cfg.autoSync
        discovered = cfg.discovered
        enabled = cfg.isEnabled
        generated = null
        message = null
        error = null
    }

    fun buildConfig(): TunnelConfig = TunnelConfig(
        id = selectedId ?: System.currentTimeMillis(),
        name = name.trim().ifBlank { copy.tunFallbackName.replace("%1", (selectedId ?: "new").toString()) },
        core = runCatching { TunnelCore.valueOf(coreName) }.getOrDefault(TunnelCore.BACKPACK),
        transport = runCatching { TunnelTransport.valueOf(transportName) }.getOrDefault(TunnelTransport.STEALTH),
        iranHost = iranHost.trim(),
        iranPort = iranPort.toIntOrNull()?.coerceIn(1, 65535) ?: 443,
        foreignHost = foreignHost.trim(),
        foreignPort = foreignPort.toIntOrNull()?.coerceIn(1, 65535) ?: 8443,
        corePort = corePort.toIntOrNull()?.coerceIn(1, 65535) ?: 3080,
        token = token.trim(),
        preset = preset.trim(),
        kcpMode = kcpMode.trim(),
        encryption = encryption.trim(),
        spoofSrcIp = spoofSrcIp.trim(),
        spoofPeerIp = spoofPeerIp.trim(),
        virtualIpIran = virtualIpIran.trim(),
        virtualIpKharej = virtualIpForeign.trim(),
        mtu = mtu.toIntOrNull()?.coerceIn(576, 9000) ?: 1350,
        acceptUdp = acceptUdp,
        proxyProtocol = proxyProtocol,
        wsPath = wsPath.trim().ifBlank { "/tunnel" },
        wsHost = wsHost.trim(),
        multiPorts = multiPorts.trim(),
        autoSync = autoSync,
        discovered = discovered,
        isEnabled = enabled
    )

    fun persist(cfg: TunnelConfig): Boolean {
        val next = records.toMutableList()
        val index = next.indexOfFirst { it.id == cfg.id }
        if (index >= 0) next[index] = cfg else next.add(cfg)
        return runCatching { Prefs.saveTunnels(context, next) }
            .onSuccess {
                records = next
                selectedId = cfg.id
            }
            .onFailure {
                error = SecretRedactor.redact(it.message ?: copy.tunCodeFailed, listOf(cfg.token)).take(300)
            }
            .isSuccess
    }

    fun saveOnly() {
        val cfg = buildConfig()
        error = null
        if (persist(cfg)) message = copy.tunSaved
    }

    fun generate() {
        val cfg = buildConfig()
        error = null
        message = null
        runCatching { TunnelEngine.generateCode(cfg) }
            .onSuccess {
                token = cfg.token
                if (persist(cfg)) {
                    generated = it
                    message = copy.tunCodeGenerated
                }
            }
            .onFailure { error = SecretRedactor.redact(it.message ?: copy.tunCodeFailed, listOf(cfg.token)).take(300) }
    }

    fun deploy(cfg: TunnelConfig) {
        if (busy) return
        error = null
        if (!persist(cfg)) return
        busy = true
        error = null
        message = copy.tunDeploying
        scope.launch {
            runCatching { TunnelEngine.autoDeployTunnel(context, cfg) }
                .onSuccess { result ->
                    token = cfg.token
                    if (persist(cfg)) {
                        val summary = SecretRedactor.redact(result.summaryMessage, listOf(cfg.token)).take(500)
                        if (result.overallSuccess) message = summary else error = summary
                        generated = null
                    }
                }
                .onFailure { error = SecretRedactor.redact(it.message ?: copy.tunDeployFailed, listOf(cfg.token)).take(300) }
            busy = false
        }
    }

    fun test() {
        val cfg = buildConfig()
        busy = true
        error = null
        scope.launch {
            runCatching { TunnelEngine.testTunnel(cfg) }
                .onSuccess { result ->
                    message = if (result.first) copy.tunReachable.replace("%1", result.second.toString()) else copy.tunUnreachable
                }
                .onFailure { error = SecretRedactor.redact(it.message ?: copy.tunProbeFailed, listOf(cfg.token)).take(300) }
            busy = false
        }
    }

    fun control(cfg: TunnelConfig, action: String) {
        if (busy || action !in setOf("start", "stop", "restart")) return
        val current = records.firstOrNull { it.id == cfg.id }
        if (current == null || current.name != cfg.name || current.iranHost != cfg.iranHost || current.foreignHost != cfg.foreignHost) {
            error = copy.tunActionFailedGeneric
            return
        }
        busy = true
        error = null
        scope.launch {
            runCatching {
                check(TunnelEngine.controlRemoteTunnel(context, cfg, action)) { copy.tunActionFailedGeneric }
            }
                .onSuccess { message = copy.tunActionDone.replace("%1", action) }
                .onFailure { error = SecretRedactor.redact(it.message ?: copy.tunActionFailedGeneric, listOf(cfg.token)).take(300) }
            busy = false
        }
    }

    val artifactOptions = listOf(
        "iran-config" to copy.tunArtifactIranConfig,
        "foreign-config" to copy.tunArtifactForeignConfig,
        "iran-install" to copy.tunArtifactIranInstall,
        "foreign-install" to copy.tunArtifactForeignInstall,
        "docker-iran" to copy.tunArtifactDockerIran,
        "docker-foreign" to copy.tunArtifactDockerForeign
    )
    val artifactLabel = artifactOptions.firstOrNull { it.first == artifact }?.second ?: copy.tunArtifactIranConfig
    val artifactText = generated?.let {
        when (artifact) {
            "foreign-config" -> it.foreignConfig
            "iran-install" -> it.iranInstallCommand
            "foreign-install" -> it.foreignInstallCommand
            "docker-iran" -> it.dockerComposeIran
            "docker-foreign" -> it.dockerComposeForeign
            else -> it.iranConfig
        }
    }.orEmpty()

    LazyColumn(Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(CommandSpacing.md)) {
        item {
            Row(Modifier.fillMaxWidth().padding(top = CommandSpacing.sm), verticalAlignment = Alignment.CenterVertically) {
                CommandBackButton(copy.back, onBack)
                CommandSectionTitle(copy.tunnels, if (selectedId == null) copy.tunNewConfiguration else copy.tunEditingId.replace("%1", selectedId.toString()), modifier = Modifier.weight(1f))
            }
        }
        item {
            CommandSurface(raised = true, modifier = Modifier.fillMaxWidth()) {
                Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(copy.tunSavedTunnels, Modifier.weight(1f), style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                        CommandTextButton(copy.tunNew, ::resetForm, icon = Icons.Rounded.Tune)
                    }
                    if (records.isEmpty()) {
                        Text(copy.tunEmptyBody, color = CommandColors.textSecondary, style = androidx.compose.material3.MaterialTheme.typography.bodySmall)
                    } else {
                        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xs)) {
                            records.forEach { cfg ->
                                CommandSecondaryButton(cfg.name, { selectTunnel(cfg) }, enabled = selectedId != cfg.id)
                            }
                        }
                    }
                }
            }
        }
        item {
            CommandSurface(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                    Text(copy.tunIdentityEngine, style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                    OutlinedTextField(name, { name = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunName) })
                    Text(copy.tunCore, color = CommandColors.textSecondary, style = androidx.compose.material3.MaterialTheme.typography.labelMedium)
                    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xs)) {
                        TunnelCore.values().forEach { core ->
                            CommandSecondaryButton(core.displayName, { coreName = core.name; generated = null }, enabled = coreName != core.name)
                        }
                    }
                    Text(copy.tunTransport, color = CommandColors.textSecondary, style = androidx.compose.material3.MaterialTheme.typography.labelMedium)
                    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xs)) {
                        TunnelTransport.values().forEach { transport ->
                            CommandSecondaryButton(transport.displayName, { transportName = transport.name; generated = null }, enabled = transportName != transport.name)
                        }
                    }
                }
            }
        }
        item {
            CommandSurface(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                    Text(copy.tunEndpoints, style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(iranHost, { iranHost = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunIranHost) })
                                OutlinedTextField(iranPort, { iranPort = it.filter(Char::isDigit).take(5) }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.port) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(iranHost, { iranHost = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunIranHost) })
                                OutlinedTextField(iranPort, { iranPort = it.filter(Char::isDigit).take(5) }, Modifier.width(100.dp), singleLine = true, label = { Text(copy.port) })
                            }
                        }
                    }
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(foreignHost, { foreignHost = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunForeignHost) })
                                OutlinedTextField(foreignPort, { foreignPort = it.filter(Char::isDigit).take(5) }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.port) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(foreignHost, { foreignHost = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunForeignHost) })
                                OutlinedTextField(foreignPort, { foreignPort = it.filter(Char::isDigit).take(5) }, Modifier.width(100.dp), singleLine = true, label = { Text(copy.port) })
                            }
                        }
                    }
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(corePort, { corePort = it.filter(Char::isDigit).take(5) }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunCorePort) })
                                OutlinedTextField(token, { token = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunRealToken) }, visualTransformation = androidx.compose.ui.text.input.PasswordVisualTransformation())
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(corePort, { corePort = it.filter(Char::isDigit).take(5) }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunCorePort) })
                                OutlinedTextField(token, { token = it }, Modifier.weight(2f), singleLine = true, label = { Text(copy.tunRealToken) }, visualTransformation = androidx.compose.ui.text.input.PasswordVisualTransformation())
                            }
                        }
                    }
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                        CommandSecondaryButton(copy.tunGenerateToken, { token = TunnelEngine.generateRandomToken(24) }, icon = Icons.Rounded.Tune)
                        Text(if (token.isBlank()) copy.tunTokenEmpty else copy.tunTokenSet, color = if (token.isBlank()) CommandColors.warning else CommandColors.success, style = androidx.compose.material3.MaterialTheme.typography.bodySmall)
                    }
                    if (discovered) Text(copy.tunDiscoveryBody, color = CommandColors.warning, style = androidx.compose.material3.MaterialTheme.typography.bodySmall)
                }
            }
        }
        item {
            CommandSurface(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                    Text(copy.tunAdvancedParams, style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(preset, { preset = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunPreset) })
                                OutlinedTextField(kcpMode, { kcpMode = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunKcpMode) })
                                OutlinedTextField(encryption, { encryption = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunEncryption) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(preset, { preset = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunPreset) })
                                OutlinedTextField(kcpMode, { kcpMode = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunKcpMode) })
                                OutlinedTextField(encryption, { encryption = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunEncryption) })
                            }
                        }
                    }
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(wsPath, { wsPath = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunWsPath) })
                                OutlinedTextField(wsHost, { wsHost = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunWsHost) })
                                OutlinedTextField(mtu, { mtu = it.filter(Char::isDigit).take(4) }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunMtu) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(wsPath, { wsPath = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunWsPath) })
                                OutlinedTextField(wsHost, { wsHost = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunWsHost) })
                                OutlinedTextField(mtu, { mtu = it.filter(Char::isDigit).take(4) }, Modifier.width(100.dp), singleLine = true, label = { Text(copy.tunMtu) })
                            }
                        }
                    }
                    OutlinedTextField(multiPorts, { multiPorts = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunMultiPortHint) })
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                CommandBooleanSetting(copy.tunAcceptUdp, acceptUdp) { acceptUdp = it }
                                CommandBooleanSetting(copy.tunProxyProtocol, proxyProtocol) { proxyProtocol = it }
                                CommandBooleanSetting(copy.tunAutoSync, autoSync) { autoSync = it }
                                CommandBooleanSetting(copy.tunEnabled, enabled) { enabled = it }
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.lg), modifier = Modifier.fillMaxWidth()) {
                                CommandBooleanSetting(copy.tunAcceptUdp, acceptUdp) { acceptUdp = it }
                                CommandBooleanSetting(copy.tunProxyProtocol, proxyProtocol) { proxyProtocol = it }
                                CommandBooleanSetting(copy.tunAutoSync, autoSync) { autoSync = it }
                                CommandBooleanSetting(copy.tunEnabled, enabled) { enabled = it }
                            }
                        }
                    }
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(spoofSrcIp, { spoofSrcIp = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunSpoofSource) })
                                OutlinedTextField(spoofPeerIp, { spoofPeerIp = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunSpoofPeer) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(spoofSrcIp, { spoofSrcIp = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunSpoofSource) })
                                OutlinedTextField(spoofPeerIp, { spoofPeerIp = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunSpoofPeer) })
                            }
                        }
                    }
                    BoxWithConstraints(Modifier.fillMaxWidth()) {
                        if (maxWidth < CommandBreakpoints.formStack) {
                            Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                                OutlinedTextField(virtualIpIran, { virtualIpIran = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunVirtualIranIp) })
                                OutlinedTextField(virtualIpForeign, { virtualIpForeign = it }, Modifier.fillMaxWidth(), singleLine = true, label = { Text(copy.tunVirtualForeignIp) })
                            }
                        } else {
                            Row(horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm), modifier = Modifier.fillMaxWidth()) {
                                OutlinedTextField(virtualIpIran, { virtualIpIran = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunVirtualIranIp) })
                                OutlinedTextField(virtualIpForeign, { virtualIpForeign = it }, Modifier.weight(1f), singleLine = true, label = { Text(copy.tunVirtualForeignIp) })
                            }
                        }
                    }
                }
            }
        }
        item {
            BoxWithConstraints(Modifier.fillMaxWidth()) {
                if (maxWidth < CommandBreakpoints.formStack) {
                    Column(verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                        CommandPrimaryButton(copy.save, ::saveOnly, Modifier.fillMaxWidth(), Icons.Rounded.Save, enabled = !busy)
                        CommandSecondaryButton(copy.tunGenerate, ::generate, Modifier.fillMaxWidth(), Icons.Rounded.Tune, enabled = !busy)
                    }
                } else {
                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                        CommandPrimaryButton(copy.save, ::saveOnly, Modifier.weight(1f), Icons.Rounded.Save, enabled = !busy)
                        CommandSecondaryButton(copy.tunGenerate, ::generate, Modifier.weight(1f), Icons.Rounded.Tune, enabled = !busy)
                    }
                }
            }
        }
        if (selectedId != null) {
            item {
                CommandSurface(raised = true, modifier = Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                        Text(copy.tunRemoteOps, style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                        Text(copy.tunActionsBody, color = CommandColors.textSecondary, style = androidx.compose.material3.MaterialTheme.typography.bodySmall)
                        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xs)) {
                            CommandPrimaryButton(copy.deploy, { confirmConfig = buildConfig(); confirmAction = TunnelConfirmAction.DEPLOY }, icon = Icons.Rounded.PlayArrow, enabled = !busy)
                            CommandSecondaryButton(copy.test, ::test, icon = Icons.Rounded.Refresh, enabled = !busy)
                            CommandSecondaryButton(copy.start, { confirmConfig = buildConfig(); confirmAction = TunnelConfirmAction.START }, icon = Icons.Rounded.PlayArrow, enabled = !busy)
                            CommandSecondaryButton(copy.stop, { confirmConfig = buildConfig(); confirmAction = TunnelConfirmAction.STOP }, icon = Icons.Rounded.Stop, enabled = !busy)
                            CommandSecondaryButton(copy.restart, { confirmConfig = buildConfig(); confirmAction = TunnelConfirmAction.RESTART }, icon = Icons.Rounded.Refresh, enabled = !busy)
                            CommandTextButton(copy.delete, { confirmConfig = buildConfig(); confirmAction = TunnelConfirmAction.DELETE }, icon = Icons.Rounded.DeleteOutline, enabled = !busy)
                        }
                    }
                }
            }
        }
        if (message != null) item { CommandStateBlock(copy.tunOperation, message ?: "", CommandHealthTone.INFO) }
        if (error != null) item { CommandStateBlock(copy.operationFailed, error ?: "", CommandHealthTone.OFFLINE) }
        if (generated != null) {
            item {
                CommandSurface(Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(CommandSpacing.md), verticalArrangement = Arrangement.spacedBy(CommandSpacing.sm)) {
                        Text(copy.tunGeneratedEvidence, style = androidx.compose.material3.MaterialTheme.typography.titleMedium, color = CommandColors.textPrimary)
                        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xs)) {
                            artifactOptions.forEach { (key, label) ->
                                CommandSecondaryButton(label, { artifact = key }, enabled = artifact != key)
                            }
                        }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(artifactLabel, Modifier.weight(1f), color = CommandColors.textSecondary)
                            CommandTextButton(copy.tunCopyArtifact, { SensitiveClipboard.copy(context, copy.tunGeneratedEvidence, artifactText) }, icon = Icons.Rounded.ContentCopy, enabled = artifactText.isNotBlank())
                        }
                        Text(artifactText.ifBlank { copy.noOutput }, color = CommandColors.textPrimary, style = androidx.compose.material3.MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace), maxLines = 60, overflow = TextOverflow.Ellipsis)
                    }
                }
            }
        }
        item { Spacer(Modifier.height(CommandSpacing.xl)) }
    }

    val actionToConfirm = confirmAction
    val configToConfirm = confirmConfig
    if (actionToConfirm != null && configToConfirm != null) {
        val action = actionToConfirm
        val cfg = configToConfirm
        val actionLabel = when (action) {
            TunnelConfirmAction.DEPLOY -> copy.deploy
            TunnelConfirmAction.START -> copy.start
            TunnelConfirmAction.STOP -> copy.stop
            TunnelConfirmAction.RESTART -> copy.restart
            TunnelConfirmAction.DELETE -> copy.delete
        }
        CommandConfirmDialog(
            title = if (action == TunnelConfirmAction.DELETE) copy.tunDeleteTitle else if (action == TunnelConfirmAction.DEPLOY) copy.tunDeployTitle else actionLabel,
            body = "${if (action == TunnelConfirmAction.DELETE) copy.tunDeleteBody else copy.tunDeployBody}\n\n${cfg.name} · #${cfg.id}\n${cfg.iranHost}:${cfg.iranPort} → ${cfg.foreignHost}:${cfg.foreignPort}\n$actionLabel",
            confirmLabel = if (action == TunnelConfirmAction.DELETE) copy.delete else actionLabel,
            dismissLabel = copy.cancel,
            onDismiss = { if (!busy) { confirmAction = null; confirmConfig = null } },
            destructive = action == TunnelConfirmAction.DELETE || action == TunnelConfirmAction.STOP,
            enabled = !busy,
            onConfirm = {
                if (!busy) {
                    confirmAction = null
                    confirmConfig = null
                    when (action) {
                        TunnelConfirmAction.DEPLOY -> deploy(cfg)
                        TunnelConfirmAction.START -> control(cfg, "start")
                        TunnelConfirmAction.STOP -> control(cfg, "stop")
                        TunnelConfirmAction.RESTART -> control(cfg, "restart")
                        TunnelConfirmAction.DELETE -> {
                            val current = records.firstOrNull { it.id == cfg.id }
                            if (current != null && current.name == cfg.name && current.iranHost == cfg.iranHost && current.foreignHost == cfg.foreignHost) {
                                busy = true
                                error = null
                                scope.launch {
                                    runCatching {
                                        check(TunnelEngine.controlRemoteTunnel(context, cfg, "delete")) { copy.tunActionFailedGeneric }
                                        val next = records.filterNot { it.id == cfg.id }
                                        Prefs.saveTunnels(context, next)
                                        next
                                    }.onSuccess { next ->
                                        records = next
                                        resetForm()
                                        message = copy.tunDeleted
                                    }.onFailure {
                                        error = SecretRedactor.redact(it.message ?: copy.tunActionFailedGeneric, listOf(cfg.token)).take(300)
                                    }
                                    busy = false
                                }
                            } else error = copy.tunActionFailedGeneric
                        }
                    }
                }
            }
        )
    }
}

@Composable
private fun CommandBooleanSetting(label: String, checked: Boolean, onChange: (Boolean) -> Unit) {
    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(CommandSpacing.xxs)) {
        Switch(checked = checked, onCheckedChange = onChange)
        Text(label, color = CommandColors.textSecondary, style = androidx.compose.material3.MaterialTheme.typography.labelSmall)
    }
}
