package org.didban.monitor

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.text.PlatformTextStyle
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.LineHeightStyle
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Blank-canvas design tokens.
 *
 * این سیستم عمداً از `Ds` و Tokenهای Aero جدا است. `Ds` تا پایان مهاجرت
 * صفحه‌های قدیمی برای Compatibility باقی می‌ماند؛ هیچ صفحهٔ جدیدی نباید از
 * آن استفاده کند.
 */
data class CommandPalette(
    val canvas: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val border: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val accent: Color,
    val onAccent: Color,
    val success: Color,
    val successSurface: Color,
    val warning: Color,
    val warningSurface: Color,
    val danger: Color,
    val dangerSurface: Color,
    val info: Color,
    val infoSurface: Color,
    val violet: Color,
    val track: Color,
    val focus: Color
)

val CommandLightPalette = CommandPalette(
    canvas = Color(0xFFF8FAFC),
    surface = Color(0xFFFFFFFF),
    surfaceRaised = Color(0xFFF1F5F9),
    border = Color(0xFFE2E8F0),
    borderStrong = Color(0xFFCBD5E1),
    textPrimary = Color(0xFF0F172A),
    textSecondary = Color(0xFF475569),
    textTertiary = Color(0xFF94A3B8),
    accent = Color(0xFF0284C7),
    onAccent = Color(0xFFFFFFFF),
    success = Color(0xFF059669),
    successSurface = Color(0xFFE7F7F0),
    warning = Color(0xFFD97706),
    warningSurface = Color(0xFFFFF7E6),
    danger = Color(0xFFDC2626),
    dangerSurface = Color(0xFFFFECEC),
    info = Color(0xFF2563EB),
    infoSurface = Color(0xFFEFF6FF),
    violet = Color(0xFF7C3AED),
    track = Color(0xFFE2E8F0),
    focus = Color(0xFF2563EB)
)

val CommandDarkPalette = CommandPalette(
    canvas = Color(0xFF07090E),
    surface = Color(0xFF0F131D),
    surfaceRaised = Color(0xFF151C28),
    border = Color(0xFF171F2C),
    borderStrong = Color(0xFF26334A),
    textPrimary = Color(0xFFF1F5F9),
    textSecondary = Color(0xFF94A3B8),
    textTertiary = Color(0xFF54627A),
    accent = Color(0xFF00E5FF),
    onAccent = Color(0xFF001318),
    success = Color(0xFF10B981),
    successSurface = Color(0xFF0C2926),
    warning = Color(0xFFF59E0B),
    warningSurface = Color(0xFF30230D),
    danger = Color(0xFFEF4444),
    dangerSurface = Color(0xFF32161D),
    info = Color(0xFF3B82F6),
    infoSurface = Color(0xFF101F3A),
    violet = Color(0xFFA855F7),
    track = Color(0xFF151C28),
    focus = Color(0xFF00E5FF)
)

val LocalCommandPalette = staticCompositionLocalOf { CommandLightPalette }

object CommandColors {
    val canvas: Color @Composable get() = LocalCommandPalette.current.canvas
    val surface: Color @Composable get() = LocalCommandPalette.current.surface
    val surfaceRaised: Color @Composable get() = LocalCommandPalette.current.surfaceRaised
    val border: Color @Composable get() = LocalCommandPalette.current.border
    val borderStrong: Color @Composable get() = LocalCommandPalette.current.borderStrong
    val textPrimary: Color @Composable get() = LocalCommandPalette.current.textPrimary
    val textSecondary: Color @Composable get() = LocalCommandPalette.current.textSecondary
    val textTertiary: Color @Composable get() = LocalCommandPalette.current.textTertiary
    val accent: Color @Composable get() = LocalCommandPalette.current.accent
    val onAccent: Color @Composable get() = LocalCommandPalette.current.onAccent
    val success: Color @Composable get() = LocalCommandPalette.current.success
    val successSurface: Color @Composable get() = LocalCommandPalette.current.successSurface
    val warning: Color @Composable get() = LocalCommandPalette.current.warning
    val warningSurface: Color @Composable get() = LocalCommandPalette.current.warningSurface
    val danger: Color @Composable get() = LocalCommandPalette.current.danger
    val dangerSurface: Color @Composable get() = LocalCommandPalette.current.dangerSurface
    val info: Color @Composable get() = LocalCommandPalette.current.info
    val infoSurface: Color @Composable get() = LocalCommandPalette.current.infoSurface
    val violet: Color @Composable get() = LocalCommandPalette.current.violet
    val track: Color @Composable get() = LocalCommandPalette.current.track
    val focus: Color @Composable get() = LocalCommandPalette.current.focus
}

object CommandSpacing {
    val xxs = 4.dp
    val xs = 8.dp
    val sm = 12.dp
    val md = 16.dp
    val lg = 24.dp
    val xl = 32.dp
    val xxl = 40.dp
}

private fun CommandPalette.materialColors(dark: Boolean): ColorScheme = if (dark) {
    darkColorScheme(
        primary = accent,
        onPrimary = onAccent,
        primaryContainer = successSurface,
        onPrimaryContainer = textPrimary,
        secondary = info,
        onSecondary = canvas,
        background = canvas,
        onBackground = textPrimary,
        surface = surface,
        onSurface = textPrimary,
        surfaceVariant = surfaceRaised,
        onSurfaceVariant = textSecondary,
        outline = border,
        outlineVariant = border
    )
} else {
    lightColorScheme(
        primary = accent,
        onPrimary = onAccent,
        primaryContainer = infoSurface,
        onPrimaryContainer = textPrimary,
        secondary = info,
        onSecondary = Color.White,
        background = canvas,
        onBackground = textPrimary,
        surface = surface,
        onSurface = textPrimary,
        surfaceVariant = surfaceRaised,
        onSurfaceVariant = textSecondary,
        outline = border,
        outlineVariant = border
    )
}

private fun commandTypography(language: String): Typography {
    val bodyFamily = if (language == "fa") Vazirmatn else Inter
    val base = TextStyle(
        fontFamily = bodyFamily,
        platformStyle = PlatformTextStyle(includeFontPadding = false),
        lineHeightStyle = LineHeightStyle(
            alignment = LineHeightStyle.Alignment.Center,
            trim = LineHeightStyle.Trim.None
        )
    )
    return Typography(
        displayLarge = base.copy(fontSize = 30.sp, lineHeight = 36.sp, fontWeight = FontWeight.Bold),
        headlineSmall = base.copy(fontSize = 22.sp, lineHeight = 28.sp, fontWeight = FontWeight.Bold),
        titleLarge = base.copy(fontSize = 18.sp, lineHeight = 24.sp, fontWeight = FontWeight.SemiBold),
        titleMedium = base.copy(fontSize = 16.sp, lineHeight = 22.sp, fontWeight = FontWeight.SemiBold),
        bodyLarge = base.copy(fontSize = 15.sp, lineHeight = 23.sp),
        bodyMedium = base.copy(fontSize = 14.sp, lineHeight = 22.sp),
        bodySmall = base.copy(fontSize = 12.sp, lineHeight = 18.sp),
        labelLarge = base.copy(fontSize = 14.sp, lineHeight = 20.sp, fontWeight = FontWeight.SemiBold),
        labelMedium = base.copy(fontSize = 12.sp, lineHeight = 16.sp, fontWeight = FontWeight.Medium),
        labelSmall = base.copy(fontSize = 11.sp, lineHeight = 16.sp, fontWeight = FontWeight.Medium)
    )
}

@Composable
fun CommandTheme(
    themeMode: String,
    language: String,
    content: @Composable () -> Unit
) {
    val systemDark = androidx.compose.foundation.isSystemInDarkTheme()
    val dark = when (themeMode) {
        "dark" -> true
        "auto" -> systemDark
        else -> false
    }
    val palette = if (dark) CommandDarkPalette else CommandLightPalette

    CompositionLocalProvider(
        LocalCommandPalette provides palette,
        LocalLayoutDirection provides if (language == "fa") LayoutDirection.Rtl else LayoutDirection.Ltr
    ) {
        MaterialTheme(
            colorScheme = palette.materialColors(dark),
            typography = commandTypography(language),
            shapes = Shapes(
                small = RoundedCornerShape(8.dp),
                medium = RoundedCornerShape(12.dp),
                large = RoundedCornerShape(16.dp)
            ),
            content = content
        )
    }
}

data class CommandCopy(
    val observe: String,
    val fleet: String,
    val operate: String,
    val diagnose: String,
    val workbench: String,
    val protect: String,
    val overview: String,
    val incidents: String,
    val servers: String,
    val serverDossier: String,
    val manageServers: String,
    val tunnels: String,
    val docker: String,
    val processes: String,
    val services: String,
    val radar: String,
    val uptime: String,
    val networkTools: String,
    val dns: String,
    val ssh: String,
    val batch: String,
    val sftp: String,
    val singlePort: String,
    val proxy: String,
    val developerLab: String,
    val vault: String,
    val alerts: String,
    val backup: String,
    val settings: String,
    val allSystems: String,
    val sync: String,
    val refreshing: String,
    val refresh: String,
    val addServer: String,
    val addTunnel: String,
    val addMonitor: String,
    val attention: String,
    val healthy: String,
    val offline: String,
    val waitingForData: String,
    val noServersTitle: String,
    val noServersBody: String,
    val openServer: String,
    val activeAttention: String,
    val recentActivity: String,
    val affectedServers: String,
    val noAttention: String,
    val noAttentionBody: String,
    val unknownState: String,
    val updated: String,
    val lastSeen: String,
    val latency: String,
    val cpu: String,
    val memory: String,
    val uptimeValue: String,
    val load: String,
    val incidentsFromLiveState: String,
    val noIncidentsTitle: String,
    val noIncidentsBody: String,
    val selectServer: String,
    val back: String,
    val close: String,
    val openExistingTool: String,
    val stagedWorkspace: String,
    val language: String,
    val theme: String,
    val light: String,
    val dark: String,
    val automatic: String,
    val pollInterval: String,
    val save: String,
    val saved: String,
    val english: String,
    val persian: String,
    val currentServer: String,
    val noServerSelected: String,
    val capabilities: String,
    val notAvailable: String,
    val retry: String,
    val dataIsStale: String,
    val start: String,
    val stop: String,
    val restart: String,
    val test: String,
    val edit: String,
    val run: String,
    val operationDone: String,
    val operationFailed: String,
    val target: String,
    val host: String,
    val port: String,
    val mode: String,
    val addTarget: String,
    val sources: String,
    val runProbe: String,
    val online: String,
    val averageCpu: String,
    val averageMemory: String,
    val telemetry: String,
    val coverage: String,
    val scoreOutOf: String,
    val nodes: String,
    val pressAgainToExit: String,
    val netIndexBody: String,
    val netQReachable: String,
    val netQReachableTools: String,
    val netQNetworkLayer: String,
    val netQNetworkLayerTools: String,
    val netQTls: String,
    val netQTlsTools: String,
    val netQDns: String,
    val netQDnsTools: String,
    val netQQuality: String,
    val netQQualityTools: String,
    val dnsIndexBody: String,
    val dnsZoneRecords: String,
    val dnsZoneRecordsBody: String,
    val dnsInspect: String,
    val dnsInspectBody: String,
    val copyAction: String,
    val selected: String,
    val notSelected: String,
    val batchSharedPassword: String,
    val batchSummary: String,
    val succeeded: String,
    val failed: String,
    val noOutput: String,
    val hostKeyChanged: String,
    val hostKeyNew: String,
    val hostKeyChangedBody: String,
    val hostKeyFirstBody: String,
    val resetTrust: String,
    val trustAndConnect: String,
    val srvNameRequired: String,
    val srvHostInvalid: String,
    val srvTokenRequired: String,
    val srvFingerprintInvalid: String,
    val srvSavedPolled: String,
    val srvConnecting: String,
    val srvFingerprintSuggested: String,
    val srvConnectFailed: String,
    val srvDossierHint: String,
    val srvDeleteTitle: String,
    val srvDeleteBody: String,
    val srvLocalDeleted: String,
    val delete: String,
    val upTargetRequired: String,
    val upKeywordRequired: String,
    val upSaved: String,
    val upTargetFirst: String,
    val upCheckDone: String,
    val upCheckFailed: String,
    val upNoMonitorYet: String,
    val upEditorBody: String,
    val upDeleteTitle: String,
    val upDeleteBody: String,
    val upDeleted: String,
    val and: String,
    val serversSearchPlaceholder: String,
    val tunnelsBody: String,
    val devLabBody: String,
    val vaultConfigUnparseable: String,
    val hostKeysStatus: String,
    val sftpBody: String,
    val netNoHost: String,
    val netNoOpenPorts: String,
    val netOnlyAnsweredPorts: String,
    val netProbeBody: String,
    val svcNoPassword: String,
    val svcFetching: String,
    val svcReadingJournal: String,
    val svcRunningAction: String,
    val svcConfirmTitle: String,
    val svcConfirmBody: String,
    val cancel: String,
    val hubObserveBody: String,
    val hubFileTransfer: String,
    val hubInspectGenerate: String,
    val hubDevTools: String,
    val hubProtectBody: String,
    val hubSecretTrust: String,
    val hubAlertDelivery: String,
    val hubDataRecovery: String,
    val hubAppBehaviour: String,
    val bandwidth: String,
    val bandwidthBody: String,
    val bandwidthRunning: String,
    val bandwidthResult: String,
    val bandwidthUnsupported: String,
    val download: String,
    val upload: String,
    val jitter: String,
    val packetLoss: String,
    val networkError: String,
    val security: String,
    val securityFirewall: String,
    val securityFirewallBody: String,
    val securityInspect: String,
    val securityPortToAllow: String,
    val securityAllow: String,
    val securityPortOpened: String,
    val securityBadPort: String,
    val securitySshPassword: String,
    val securityNeedPassword: String,
    val securityBans: String,
    val securityBansBody: String,
    val securityNoBans: String,
    val securityNoBansBody: String,
    val securityNoFail2ban: String,
    val securityUnban: String,
    val securityUnbanned: String,
    val securityBadValue: String,
    val radarSyncAll: String,
    val radarSyncAllBody: String,
    val radarSynced: String,
    val radarNoTargets: String,
    val radarNoTargetsBody: String,
    val vantagePhone: String
) {
    companion object {
        val fa = CommandCopy(
            observe = "پایش",
            fleet = "ناوگان",
            operate = "عملیات",
            diagnose = "تشخیص",
            workbench = "کارگاه",
            protect = "حفاظت",
            overview = "نمای کلی",
            incidents = "رخدادها",
            servers = "سرورها",
            serverDossier = "پروندهٔ سرور",
            manageServers = "مدیریت اتصال‌ها",
            tunnels = "تونل‌ها",
            docker = "Docker",
            processes = "پردازش‌ها",
            services = "سرویس‌ها",
            radar = "Radar سرور",
            uptime = "پایش دسترس‌پذیری",
            networkTools = "ابزارهای شبکه",
            dns = "DNS و Cloudflare",
            ssh = "SSH",
            batch = "اجرای گروهی",
            sftp = "SFTP",
            singlePort = "Single-Port",
            proxy = "Proxy Inspector",
            developerLab = "Developer Lab",
            vault = "Vault",
            alerts = "کانال‌های هشدار",
            backup = "Backup و Restore",
            settings = "تنظیمات",
            allSystems = "همهٔ سامانه‌ها",
            sync = "همگام‌سازی",
            refreshing = "در حال تازه‌سازی",
            refresh = "تازه‌سازی",
            addServer = "افزودن سرور",
            addTunnel = "افزودن تونل",
            addMonitor = "افزودن Monitor",
            attention = "نیازمند توجه",
            healthy = "سالم",
            offline = "آفلاین",
            waitingForData = "در انتظار دادهٔ واقعی",
            noServersTitle = "هنوز سروری متصل نیست",
            noServersBody = "برای شروع، یک Agent واقعی را به ناوگان اضافه کنید. دادهٔ نمونه نمایش داده نمی‌شود.",
            openServer = "باز کردن پرونده",
            activeAttention = "صف انتظار عملیات",
            recentActivity = "وضعیت‌های اخیر",
            affectedServers = "سرورهای درگیر",
            noAttention = "مورد فوری وجود ندارد",
            noAttentionBody = "در دادهٔ فعلی، وضعیت نیازمند توجهی از Agentها دریافت نشده است.",
            unknownState = "نامشخص",
            updated = "به‌روزرسانی",
            lastSeen = "آخرین مشاهده",
            latency = "تأخیر",
            cpu = "CPU",
            memory = "حافظه",
            uptimeValue = "Uptime",
            load = "Load",
            incidentsFromLiveState = "این فهرست از وضعیت زنده و Thresholdهای فعلی ساخته شده است؛ تاریخچهٔ کامل رخداد در مرحلهٔ Incident History اضافه می‌شود.",
            noIncidentsTitle = "رخداد فعالی ثبت نشده است",
            noIncidentsBody = "وقتی Agent یا Uptime وضعیت غیرعادی واقعی گزارش کند، اینجا قابل پیگیری خواهد بود.",
            selectServer = "انتخاب سرور",
            back = "بازگشت",
            close = "بستن",
            openExistingTool = "باز کردن قابلیت موجود",
            stagedWorkspace = "این Workspace در مرحلهٔ بعدی منتقل می‌شود.",
            language = "زبان",
            theme = "تم",
            light = "روشن",
            dark = "تیره",
            automatic = "خودکار",
            pollInterval = "فاصلهٔ پایش، ثانیه",
            save = "ذخیره",
            saved = "ذخیره شد",
            english = "English",
            persian = "فارسی",
            currentServer = "سرور انتخاب‌شده",
            noServerSelected = "بدون محدودهٔ سرور",
            capabilities = "قابلیت‌ها",
            notAvailable = "در Agent فعلی در دسترس نیست",
            retry = "تلاش دوباره",
            dataIsStale = "داده قدیمی است",
            start = "شروع",
            stop = "توقف",
            restart = "راه‌اندازی مجدد",
            test = "آزمون",
            edit = "ویرایش",
            run = "اجرا",
            operationDone = "عملیات با موفقیت انجام شد",
            operationFailed = "عملیات ناموفق بود",
            target = "هدف",
            host = "Host",
            port = "Port",
            mode = "Mode",
            addTarget = "افزودن هدف",
            sources = "منابع Probe",
            runProbe = "اجرای Probe",
            online = "آنلاین",
            averageCpu = "میانگین CPU",
            averageMemory = "میانگین حافظه",
            telemetry = "تله‌متری",
            coverage = "پوشش داده",
            scoreOutOf = "از ۱۰۰",
            nodes = "گره",
            pressAgainToExit = "برای خروج، دوباره Back بزنید",
            netIndexBody = "هر ابزار با سؤال تشخیصی خودش شروع می‌شود.",
            netQReachable = "آیا مقصد از این Server قابل دسترسی است؟",
            netQReachableTools = "TCP، HTTP، SSL و Check-Host",
            netQNetworkLayer = "آیا مشکل در لایهٔ شبکه است؟",
            netQNetworkLayerTools = "DPI، Port Scanner و TCP Ping",
            netQTls = "گواهی و هویت TLS درست است؟",
            netQTlsTools = "Subject، Chain، SAN و Fingerprint",
            netQDns = "DNS چه پاسخی می‌دهد؟",
            netQDnsTools = "Recordها و Cloudflare",
            netQQuality = "کیفیت اتصال چقدر است؟",
            netQQualityTools = "Latency، Loss، Jitter و Bandwidth",
            dnsIndexBody = "تشخیص پاسخ DNS از مدیریت Record جداست.",
            dnsZoneRecords = "مدیریت Zone و Record",
            dnsZoneRecordsBody = "ساخت، ویرایش و حذف Recordهای واقعی Cloudflare",
            dnsInspect = "بررسی پاسخ DNS",
            dnsInspectBody = "Resolve، Reverse DNS و Recordهای عمومی",
            copyAction = "کپی",
            selected = "انتخاب‌شده",
            notSelected = "انتخاب‌نشده",
            batchSharedPassword = "SSH Password مشترک",
            batchSummary = "%1 موفق · %2 ناموفق",
            succeeded = "موفق",
            failed = "ناموفق",
            noOutput = "بدون خروجی",
            hostKeyChanged = "کلید SSH تغییر کرده است",
            hostKeyNew = "اعتماد به کلید SSH جدید",
            hostKeyChangedBody = "کلید فعلی با Trust Store یکسان نیست. فقط در صورت تأیید مستقل، اعتماد را بازنشانی کنید.",
            hostKeyFirstBody = "این اولین اتصال است. Fingerprint زیر ذخیره خواهد شد.",
            resetTrust = "بازنشانی اعتماد",
            trustAndConnect = "اعتماد و اتصال",
            srvNameRequired = "نام اتصال اجباری است.",
            srvHostInvalid = "Host باید hostname یا IPv4 معتبر باشد.",
            srvTokenRequired = "Agent token اجباری است.",
            srvFingerprintInvalid = "Fingerprint TLS معتبر نیست.",
            srvSavedPolled = "اتصال ذخیره شد؛ Polling واقعی برای آن درخواست شد.",
            srvConnecting = "در حال اتصال به Agent واقعی...",
            srvFingerprintSuggested = "Agent پاسخ داد؛ fingerprint فقط به‌صورت پیشنهادی در فرم قرار گرفت و تا Save pin نمی‌شود.",
            srvConnectFailed = "اتصال به Agent ناموفق بود.",
            srvDossierHint = "از اینجا پروندهٔ واقعی سرور باز می‌شود؛ حذف فقط local connection را حذف می‌کند.",
            srvDeleteTitle = "Delete connection؟",
            srvDeleteBody = "اتصال %1 از Prefs حذف می‌شود؛ چیزی روی خود سرور حذف نخواهد شد.",
            srvLocalDeleted = "اتصال local حذف شد.",
            delete = "حذف",
            upTargetRequired = "Target نمی‌تواند خالی باشد.",
            upKeywordRequired = "برای KEYWORD باید keyword واقعی وارد شود.",
            upSaved = "Monitor ذخیره شد؛ check بعدی توسط UptimeEngine انجام می‌شود.",
            upTargetFirst = "ابتدا target را وارد کنید.",
            upCheckDone = "Check واقعی انجام شد: %1 · %2 ms",
            upCheckFailed = "Check ناموفق بود.",
            upNoMonitorYet = "هنوز Monitor واقعی ذخیره نشده است.",
            upEditorBody = "URL/HTTP و SSL از engine واقعی استفاده می‌کنند؛ target نمونه یا synthetic result ساخته نمی‌شود.",
            upDeleteTitle = "Delete monitor؟",
            upDeleteBody = "%1 و heartbeat/incidentهای محلی آن حذف می‌شوند.",
            upDeleted = "Monitor حذف شد.",
            and = "و",
            serversSearchPlaceholder = "جستجوی نام یا Host",
            tunnelsBody = "ساخت و ویرایش تنظیمات از همین مسیر انجام می‌شود؛ Save محلی است و Deploy جداگانه تأیید می‌خواهد.",
            devLabBody = "این ابزار هیچ input ساختگی مصرف نمی‌کند؛ خروجی با SecureRandom و UUID واقعی تولید می‌شود.",
            vaultConfigUnparseable = "Config قابل parse نیست",
            hostKeysStatus = "%d entries · Trust Store فعال است",
            sftpBody = "SFTP از Trust Store محلی استفاده می‌کند؛ اولین کلید سرور به‌صورت TOFU ثبت می‌شود و تغییر بعدی اتصال را رد می‌کند.",
            netNoHost = "Host یا domain وارد نشده است.",
            netNoOpenPorts = "هیچ پورت باز از مجموعهٔ common portها پاسخ نداد.",
            netOnlyAnsweredPorts = "فقط پورت‌هایی که واقعاً پاسخ دادند نمایش داده می‌شوند.",
            netProbeBody = "Probe از دستگاه فعلی اجرا می‌شود؛ نتیجه فقط پس از پاسخ واقعی شبکه نمایش داده می‌شود.",
            svcNoPassword = "رمز SSH وارد نشده است.",
            svcFetching = "در حال دریافت سرویس‌ها",
            svcReadingJournal = "در حال خواندن Journal",
            svcRunningAction = "در حال اجرای %s",
            svcConfirmTitle = "تأیید %1 روی %2",
            svcConfirmBody = "این عملیات مستقیماً روی سرویس واقعی سرور اجرا می‌شود. خروجی خام SSH بعد از اجرا نمایش داده خواهد شد.",
            cancel = "لغو",
            hubObserveBody = "از سؤال عملیاتی شروع کنید؛ ابزار فقط در Context لازم باز می‌شود.",
            hubFileTransfer = "انتقال فایل",
            hubInspectGenerate = "بررسی و تولید",
            hubDevTools = "ابزارهای توسعه",
            hubProtectBody = "اطلاعات حساس، اعلان‌ها و بازیابی داده در یک فضای جدا از عملیات عادی.",
            hubSecretTrust = "Secret و Trust",
            hubAlertDelivery = "تحویل هشدار",
            hubDataRecovery = "داده و بازیابی",
            hubAppBehaviour = "رفتار برنامه",
            bandwidth = "سنجش پهنای باند",
            bandwidthBody = "دانلود و آپلود واقعی ۱۰۰ مگابایت از/به ایجنت، به‌همراه تأخیر، جیتر و افت بسته.",
            bandwidthRunning = "در حال سنجش…",
            bandwidthResult = "نتیجهٔ سنجش",
            bandwidthUnsupported = "ایجنت این سرور از سنجش پهنای باند پشتیبانی نمی‌کند؛ ایجنت را به‌روزرسانی کنید.",
            download = "دانلود",
            upload = "آپلود",
            jitter = "جیتر",
            packetLoss = "افت بسته",
            networkError = "خطای شبکه",
            security = "امنیت سرور",
            securityFirewall = "دیوار آتش",
            securityFirewallBody = "وضعیت ufw یا iptables و باز کردن پورت",
            securityInspect = "بررسی دیوار آتش",
            securityPortToAllow = "پورت",
            securityAllow = "باز کن",
            securityPortOpened = "پورت %d باز شد",
            securityBadPort = "شمارهٔ پورت معتبر نیست (۱ تا ۶۵۵۳۵)",
            securitySshPassword = "رمز SSH",
            securityNeedPassword = "رمز SSH را وارد کنید",
            securityBans = "مسدودی‌های fail2ban",
            securityBansBody = "فهرست زندان‌ها و آدرس‌های مسدودشده",
            securityNoBans = "هیچ آدرسی مسدود نیست",
            securityNoBansBody = "fail2ban در حال اجراست ولی زندان‌ها خالی‌اند.",
            securityNoFail2ban = "fail2ban روی این سرور نصب یا فعال نیست.",
            securityUnban = "آزاد کن",
            securityUnbanned = "آدرس %s آزاد شد",
            securityBadValue = "آدرس IP یا نام زندان نامعتبر است",
            radarSyncAll = "همگام‌سازی پایش‌ها",
            radarSyncAllBody = "همهٔ پایش‌های آپ‌تایم را به این ایجنت می‌فرستد تا از دید سرور هم بررسی شوند.",
            radarSynced = "%d پایش همگام شد",
            radarNoTargets = "پایشی برای همگام‌سازی نیست",
            radarNoTargetsBody = "ابتدا در «پایش دسترس‌پذیری» یک پایش بسازید.",
            vantagePhone = "گوشی"
        )

        val en = fa.copy(
            observe = "Observe",
            fleet = "Fleet",
            operate = "Operate",
            diagnose = "Diagnose",
            workbench = "Workbench",
            protect = "Protect",
            overview = "Overview",
            incidents = "Incidents",
            servers = "Servers",
            serverDossier = "Server dossier",
            manageServers = "Manage connections",
            tunnels = "Tunnels",
            processes = "Processes",
            services = "Services",
            radar = "Server Radar",
            uptime = "Uptime",
            networkTools = "Network tools",
            dns = "DNS and Cloudflare",
            ssh = "SSH",
            batch = "Batch execution",
            developerLab = "Developer Lab",
            vault = "Vault",
            alerts = "Alert delivery",
            backup = "Backup and Restore",
            settings = "Settings",
            allSystems = "All systems",
            sync = "Sync",
            refreshing = "Refreshing",
            refresh = "Refresh",
            addServer = "Add server",
            addTunnel = "Add tunnel",
            addMonitor = "Add monitor",
            attention = "Needs attention",
            healthy = "Healthy",
            offline = "Offline",
            waitingForData = "Waiting for real data",
            noServersTitle = "No server is connected yet",
            noServersBody = "Connect a real Agent to begin. Sample data is never shown.",
            openServer = "Open dossier",
            activeAttention = "Operations queue",
            recentActivity = "Recent state",
            affectedServers = "Affected servers",
            noAttention = "Nothing needs attention",
            noAttentionBody = "No abnormal state has been reported by the current Agents.",
            unknownState = "Unknown",
            updated = "Updated",
            lastSeen = "Last seen",
            latency = "Latency",
            memory = "Memory",
            uptimeValue = "Uptime",
            load = "Load",
            incidentsFromLiveState = "This list is derived from live state and current thresholds; full incident history will be added in the Incident History stage.",
            noIncidentsTitle = "No active incident",
            noIncidentsBody = "Real abnormal state from an Agent or Uptime monitor will appear here.",
            selectServer = "Select server",
            back = "Back",
            close = "Close",
            openExistingTool = "Open existing capability",
            stagedWorkspace = "This workspace will be migrated in the next stage.",
            language = "Language",
            theme = "Theme",
            light = "Light",
            dark = "Dark",
            automatic = "Automatic",
            pollInterval = "Poll interval, seconds",
            save = "Save",
            saved = "Saved",
            english = "English",
            persian = "فارسی",
            currentServer = "Selected server",
            noServerSelected = "No server scope",
            capabilities = "Capabilities",
            notAvailable = "Not available from this Agent",
            retry = "Retry",
            dataIsStale = "Data is stale",
            start = "Start",
            stop = "Stop",
            restart = "Restart",
            test = "Test",
            edit = "Edit",
            run = "Run",
            operationDone = "Operation completed",
            operationFailed = "Operation failed",
            target = "Target",
            host = "Host",
            port = "Port",
            mode = "Mode",
            addTarget = "Add target",
            sources = "Probe sources",
            runProbe = "Run probe",
            online = "Online",
            averageCpu = "Average CPU",
            averageMemory = "Average memory",
            telemetry = "Telemetry",
            coverage = "Data coverage",
            scoreOutOf = "OUT OF 100",
            nodes = "nodes",
            pressAgainToExit = "Press back again to exit",
            netIndexBody = "Every tool starts from its own diagnostic question.",
            netQReachable = "Is the destination reachable from this server?",
            netQReachableTools = "TCP, HTTP, SSL and Check-Host",
            netQNetworkLayer = "Is the problem at the network layer?",
            netQNetworkLayerTools = "DPI, port scanner and TCP ping",
            netQTls = "Is the TLS certificate and identity correct?",
            netQTlsTools = "Subject, chain, SAN and fingerprint",
            netQDns = "What does DNS answer?",
            netQDnsTools = "Records and Cloudflare",
            netQQuality = "How good is the connection?",
            netQQualityTools = "Latency, loss, jitter and bandwidth",
            dnsIndexBody = "Diagnosing a DNS answer is separate from managing records.",
            dnsZoneRecords = "Zone and record management",
            dnsZoneRecordsBody = "Create, edit and delete real Cloudflare records",
            dnsInspect = "Inspect a DNS answer",
            dnsInspectBody = "Resolve, reverse DNS and public records",
            copyAction = "Copy",
            selected = "Selected",
            notSelected = "Not selected",
            batchSharedPassword = "Shared SSH password",
            batchSummary = "%1 succeeded · %2 failed",
            succeeded = "Succeeded",
            failed = "Failed",
            noOutput = "No output",
            hostKeyChanged = "The SSH host key has changed",
            hostKeyNew = "Trust the new SSH host key",
            hostKeyChangedBody = "The presented key does not match the trust store. Only reset trust after verifying it independently.",
            hostKeyFirstBody = "This is the first connection. The fingerprint below will be stored.",
            resetTrust = "Reset trust",
            trustAndConnect = "Trust and connect",
            srvNameRequired = "Connection name is required.",
            srvHostInvalid = "Host must be a valid hostname or IPv4 address.",
            srvTokenRequired = "Agent token is required.",
            srvFingerprintInvalid = "TLS fingerprint is not valid.",
            srvSavedPolled = "Connection saved; a real poll was requested for it.",
            srvConnecting = "Connecting to the real agent…",
            srvFingerprintSuggested = "The agent replied; the fingerprint is only suggested in the form and is not pinned until you save.",
            srvConnectFailed = "Connecting to the agent failed.",
            srvDossierHint = "The server's real dossier opens from here; delete only removes the local connection.",
            srvDeleteTitle = "Delete connection?",
            srvDeleteBody = "The connection to %1 is removed from local preferences; nothing is deleted on the server itself.",
            srvLocalDeleted = "Local connection deleted.",
            delete = "Delete",
            upTargetRequired = "Target cannot be empty.",
            upKeywordRequired = "A KEYWORD monitor needs a real keyword.",
            upSaved = "Monitor saved; the next check runs in UptimeEngine.",
            upTargetFirst = "Enter a target first.",
            upCheckDone = "Real check completed: %1 · %2 ms",
            upCheckFailed = "The check failed.",
            upNoMonitorYet = "No real monitor has been saved yet.",
            upEditorBody = "URL/HTTP and SSL use the real engine; no sample target or synthetic result is produced.",
            upDeleteTitle = "Delete monitor?",
            upDeleteBody = "%1 and its local heartbeats and incidents are deleted.",
            upDeleted = "Monitor deleted.",
            and = "and",
            serversSearchPlaceholder = "Search by name or host",
            tunnelsBody = "Create and edit tunnel configuration from here. Save is local; deploy asks for separate confirmation.",
            devLabBody = "This tool consumes no synthetic input: output comes from SecureRandom and real UUIDs.",
            vaultConfigUnparseable = "Config cannot be parsed",
            hostKeysStatus = "%d entries · trust store active",
            sftpBody = "SFTP uses the local trust store: the first server key is recorded as TOFU and a later change rejects the connection.",
            netNoHost = "No host or domain entered.",
            netNoOpenPorts = "No port in the common set responded.",
            netOnlyAnsweredPorts = "Only ports that actually responded are shown.",
            netProbeBody = "The probe runs from this device; results appear only after a real network response.",
            svcNoPassword = "No SSH password entered.",
            svcFetching = "Fetching services",
            svcReadingJournal = "Reading journal",
            svcRunningAction = "Running %s",
            svcConfirmTitle = "Confirm %1 on %2",
            svcConfirmBody = "This runs directly on the server's real service. The raw SSH output is shown after it completes.",
            cancel = "Cancel",
            hubObserveBody = "Start from an operational question; tools open only in the context that needs them.",
            hubFileTransfer = "File transfer",
            hubInspectGenerate = "Inspect & generate",
            hubDevTools = "Developer tools",
            hubProtectBody = "Secrets, alerts and data recovery live in a space separate from routine operations.",
            hubSecretTrust = "Secrets & trust",
            hubAlertDelivery = "Alert delivery",
            hubDataRecovery = "Data & recovery",
            hubAppBehaviour = "App behaviour",
            bandwidth = "Bandwidth benchmark",
            bandwidthBody = "A real 100 MiB download from and upload to the agent, plus latency, jitter and packet loss.",
            bandwidthRunning = "Measuring…",
            bandwidthResult = "Benchmark result",
            bandwidthUnsupported = "This server's agent does not support the bandwidth benchmark; update the agent.",
            download = "Download",
            upload = "Upload",
            jitter = "Jitter",
            packetLoss = "Packet loss",
            networkError = "Network error",
            security = "Server security",
            securityFirewall = "Firewall",
            securityFirewallBody = "ufw or iptables state, and opening a port",
            securityInspect = "Inspect firewall",
            securityPortToAllow = "Port",
            securityAllow = "Allow",
            securityPortOpened = "Port %d opened",
            securityBadPort = "Invalid port number (1-65535)",
            securitySshPassword = "SSH password",
            securityNeedPassword = "Enter the SSH password",
            securityBans = "fail2ban bans",
            securityBansBody = "The jails and the addresses they have banned",
            securityNoBans = "No banned addresses",
            securityNoBansBody = "fail2ban is running but its jails are empty.",
            securityNoFail2ban = "fail2ban is not installed or running on this server.",
            securityUnban = "Unban",
            securityUnbanned = "Unbanned %s",
            securityBadValue = "Invalid IP address or jail name",
            radarSyncAll = "Sync monitors",
            radarSyncAllBody = "Pushes every uptime monitor to this agent so each one is also checked from the server's vantage point.",
            radarSynced = "Synced %d monitors",
            radarNoTargets = "No monitors to sync",
            radarNoTargetsBody = "Create a monitor under Uptime first.",
            vantagePhone = "Phone"
        )

        fun forLanguage(language: String): CommandCopy = if (language == "fa") fa else en
    }
}
