package org.didban.monitor

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.UUID

data class SinglePortRoute(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val sni: String,
    val localPort: Int,
    val useProxyProtocol: Boolean = false,
    val description: String = ""
)

data class SinglePortConfig(
    val bindPort: Int = 443,
    val inspectDelaySec: Int = 5,
    val panelDomain: String = "panel.example.com",
    val panelLocalPort: Int = 10000,
    val subTlsDomain: String = "sub.example.com",
    val subTlsLocalPort: Int = 11000,
    val realitySni: String = "yahoo.com",
    val realityLocalPort: Int = 12000,
    val realityProxyProtocol: Boolean = true,
    val fallbackLocalPort: Int = 13000,
    val customRoutes: List<SinglePortRoute> = emptyList()
)

data class DeployStatusStep(
    val title: String,
    val isDone: Boolean = false,
    val isError: Boolean = false,
    val detail: String = ""
)

object SinglePortEngine {

    /**
     * Generates a battle-tested, high-performance /etc/haproxy/haproxy.cfg configuration
     * optimized for PasarGuard, Marzban, Xray, and REALITY SNI multiplexing.
     */
    fun generateHaproxyCfg(cfg: SinglePortConfig): String {
        val sb = StringBuilder()

        sb.appendLine("# ─────────────────────────────────────────────────────────────────")
        sb.appendLine("#  HAProxy Single-Port Multiplexer Configuration")
        sb.appendLine("#  Generated by Didban (دیدبان) for PasarGuard / Xray / REALITY")
        sb.appendLine("# ─────────────────────────────────────────────────────────────────")
        sb.appendLine()
        sb.appendLine("global")
        sb.appendLine("    log /dev/log local0 info")
        sb.appendLine("    log /dev/log local1 notice")
        sb.appendLine("    chroot /var/lib/haproxy")
        sb.appendLine("    user haproxy")
        sb.appendLine("    group haproxy")
        sb.appendLine("    daemon")
        sb.appendLine("    maxconn 32768")
        sb.appendLine("    tune.bufsize 32768")
        sb.appendLine("    ssl-default-bind-ciphers PROFILE=SYSTEM")
        sb.appendLine("    ssl-default-server-ciphers PROFILE=SYSTEM")
        sb.appendLine()
        sb.appendLine("defaults")
        sb.appendLine("    log global")
        sb.appendLine("    mode tcp")
        sb.appendLine("    option tcplog")
        sb.appendLine("    option dontlognull")
        sb.appendLine("    timeout connect 5s")
        sb.appendLine("    timeout client  50s")
        sb.appendLine("    timeout server  50s")
        sb.appendLine("    timeout tunnel  1h")
        sb.appendLine()
        sb.appendLine("# ── Front-End Multiplexer (Single Port ${cfg.bindPort}) ──")
        sb.appendLine("frontend single_port_inbound")
        sb.appendLine("    bind *:${cfg.bindPort}")
        sb.appendLine("    mode tcp")
        sb.appendLine("    tcp-request inspect-delay ${cfg.inspectDelaySec}s")
        sb.appendLine("    tcp-request content accept if { req_ssl_hello_type 1 }")
        sb.appendLine()

        // Rules
        if (cfg.panelDomain.isNotBlank()) {
            sb.appendLine("    # 1. PasarGuard Web Panel & Subscription")
            sb.appendLine("    use_backend backend_panel if { req_ssl_sni -i ${cfg.panelDomain.trim()} }")
        }

        if (cfg.subTlsDomain.isNotBlank()) {
            sb.appendLine("    # 2. TLS / WS / gRPC Inbounds")
            sb.appendLine("    use_backend backend_sub_tls if { req_ssl_sni -i ${cfg.subTlsDomain.trim()} }")
        }

        if (cfg.realitySni.isNotBlank()) {
            sb.appendLine("    # 3. REALITY Camouflage SNI")
            val realitySnisArray = cfg.realitySni.split(",").map { it.trim() }.filter { it.isNotEmpty() }
            if (realitySnisArray.size > 1) {
                val snisFormatted = realitySnisArray.joinToString(" ")
                sb.appendLine("    use_backend backend_reality if { req_ssl_sni -i $snisFormatted }")
            } else {
                sb.appendLine("    use_backend backend_reality if { req_ssl_sni -i ${cfg.realitySni.trim()} }")
            }
        }

        // Custom extra routes
        cfg.customRoutes.forEachIndexed { idx, route ->
            if (route.sni.isNotBlank()) {
                sb.appendLine("    # Custom Route ${idx + 1}: ${route.name}")
                sb.appendLine("    use_backend backend_custom_${idx + 1} if { req_ssl_sni -i ${route.sni.trim()} }")
            }
        }

        sb.appendLine()
        sb.appendLine("    # Default Fallback (anti-probing & unidentified SNIs)")
        sb.appendLine("    default_backend backend_fallback")
        sb.appendLine()

        // Backends
        if (cfg.panelDomain.isNotBlank()) {
            sb.appendLine("backend backend_panel")
            sb.appendLine("    mode tcp")
            sb.appendLine("    server srv_panel 127.0.0.1:${cfg.panelLocalPort}")
            sb.appendLine()
        }

        if (cfg.subTlsDomain.isNotBlank()) {
            sb.appendLine("backend backend_sub_tls")
            sb.appendLine("    mode tcp")
            sb.appendLine("    server srv_sub_tls 127.0.0.1:${cfg.subTlsLocalPort} send-proxy")
            sb.appendLine()
        }

        if (cfg.realitySni.isNotBlank()) {
            sb.appendLine("backend backend_reality")
            sb.appendLine("    mode tcp")
            val sendProxyFlag = if (cfg.realityProxyProtocol) " send-proxy" else ""
            sb.appendLine("    server srv_reality 127.0.0.1:${cfg.realityLocalPort}$sendProxyFlag")
            sb.appendLine()
        }

        cfg.customRoutes.forEachIndexed { idx, route ->
            sb.appendLine("backend backend_custom_${idx + 1}")
            sb.appendLine("    mode tcp")
            val flag = if (route.useProxyProtocol) " send-proxy" else ""
            sb.appendLine("    server srv_custom_${idx + 1} 127.0.0.1:${route.localPort}$flag")
            sb.appendLine()
        }

        sb.appendLine("backend backend_fallback")
        sb.appendLine("    mode tcp")
        sb.appendLine("    server srv_fallback 127.0.0.1:${cfg.fallbackLocalPort}")

        return sb.toString()
    }

    /**
     * Generates a 1-line self-executing bash script for rapid manual execution in server terminal.
     */
    fun generateBashScript(cfg: SinglePortConfig): String {
        val rawCfg = generateHaproxyCfg(cfg)
        val b64Cfg = android.util.Base64.encodeToString(rawCfg.toByteArray(Charsets.UTF_8), android.util.Base64.NO_WRAP)

        return """
#!/bin/bash
# ── Didban Single-Port 1-Click Auto-Deployer for PasarGuard & Xray ──
set -e

echo "🚀 [1/4] Installing HAProxy..."
if ! command -v haproxy &> /dev/null; then
    apt-get update -qq && apt-get install -y -qq haproxy
fi

echo "📦 [2/4] Backing up old configuration..."
[ -f /etc/haproxy/haproxy.cfg ] && cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak_didban

echo "⚙️ [3/4] Writing new Single-Port HAProxy configuration..."
echo "$b64Cfg" | base64 -d > /etc/haproxy/haproxy.cfg

echo "🧪 [4/4] Validating and starting HAProxy service..."
haproxy -c -f /etc/haproxy/haproxy.cfg
systemctl enable --now haproxy
systemctl restart haproxy

echo "✅ HAProxy Single-Port is UP and LISTENING on port ${cfg.bindPort}!"
        """.trimIndent()
    }

    /**
     * Generates a Docker-Compose configuration for containerized deployments.
     */
    fun generateDockerCompose(cfg: SinglePortConfig): String {
        return """
version: '3.8'

services:
  haproxy:
    image: haproxy:alpine
    container_name: didban_single_port
    restart: always
    network_mode: host
    volumes:
      - /etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        """.trimIndent()
    }

    /**
     * Deploys HAProxy and configuration directly to remote Linux server via SSH.
     */
    suspend fun deployToRemote(
        host: String,
        port: Int = 22,
        user: String = "root",
        password: String,
        config: SinglePortConfig,
        onProgress: (step: String, isDone: Boolean, isError: Boolean, log: String) -> Unit
    ): Boolean = withContext(Dispatchers.IO) {
        try {
            onProgress("در حال بررسی و نصب HAProxy...", false, false, "")
            val installCmd = "which haproxy || (apt-get update -qq && apt-get install -y -qq haproxy)"
            val res1 = SshEngine.execute(host, port, user, password, installCmd, timeoutSec = 60)
            if (!res1.isSuccess && res1.exitCode != 0) {
                onProgress("خطا در نصب HAProxy", true, true, res1.stderr)
                return@withContext false
            }
            onProgress("✅ پکیج HAProxy آماده است", true, false, res1.stdout)

            onProgress("در حال بارگذاری و نوشتن کانفیگ /etc/haproxy/haproxy.cfg...", false, false, "")
            val rawCfg = generateHaproxyCfg(config)
            val b64 = android.util.Base64.encodeToString(rawCfg.toByteArray(Charsets.UTF_8), android.util.Base64.NO_WRAP)
            val writeCmd = "cp -n /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak_didban 2>/dev/null || true; echo '$b64' | base64 -d > /etc/haproxy/haproxy.cfg"
            val res2 = SshEngine.execute(host, port, user, password, writeCmd, timeoutSec = 20)
            if (!res2.isSuccess && res2.exitCode != 0) {
                onProgress("خطا در ذخیره کانفیگ HAProxy", true, true, res2.stderr)
                return@withContext false
            }
            onProgress("✅ فایل کانفیگ نوشته شد", true, false, "")

            onProgress("در حال اعتبارسنجی سینتکس و راه‌اندازی سرویس...", false, false, "")
            val checkAndStartCmd = "haproxy -c -f /etc/haproxy/haproxy.cfg && systemctl enable haproxy && systemctl restart haproxy && systemctl is-active haproxy"
            val res3 = SshEngine.execute(host, port, user, password, checkAndStartCmd, timeoutSec = 25)
            if (!res3.isSuccess && res3.exitCode != 0) {
                onProgress("خطا در راه‌اندازی HAProxy", true, true, res3.stderr)
                return@withContext false
            }

            onProgress("🎉 استقرار تک‌پورت کامل شد و پورت ${config.bindPort} فعال است!", true, false, "Status: ${res3.stdout.trim()}")
            true
        } catch (e: Exception) {
            onProgress("خطا در اتصال یا اجرا: ${e.message}", true, true, e.message ?: "")
            false
        }
    }
}
