package org.didban.monitor

/** UI strings in both languages — the whole app reads from an instance of this. */
class Str(
    val appName: String,
    val servers: String,
    val noServers: String,
    val noServersHint: String,
    val addServer: String,
    val monitoringOn: String,
    val monitoringOff: String,
    val langButton: String,
    val manual: String,
    val sshInstall: String,
    val sshInstallHint: String,
    val name: String,
    val host: String,
    val port: String,
    val token: String,
    val useTls: String,
    val fingerprint: String,
    val fingerprintOptional: String,
    val pinCert: String,
    val pinCertHint: String,
    val sshUser: String,
    val sshPassword: String,
    val install: String,
    val installing: String,
    val cancel: String,
    val save: String,
    val close: String,
    val delete: String,
    val confirmDelete: String,
    val back: String,
    val overview: String,
    val processes: String,
    val events: String,
    val cpu: String,
    val memory: String,
    val user: String,
    val system: String,
    val iowait: String,
    val steal: String,
    val swap: String,
    val disks: String,
    val network: String,
    val load: String,
    val uptime: String,
    val cores: String,
    val noData: String,
    val connecting: String,
    val error: String,
    val lastUpdate: String,
    val whatAteCpu: String,
    val spikeCpu: String,
    val spikeMem: String,
    val topProcesses: String,
    val offline: String,
    val serverSaved: String,
    val installDone: String,
    val installFailed: String,
    val requiresRoot: String,
    val available: String,
    val used: String,
    val yes: String,
    val no: String,
    val eventProcessDown: String,
    val eventProcessUp: String,
    val eventDisk: String,
    val eventSteal: String,
    val eventAgentRestart: String,
    val edit: String,
    val share: String,
    val latency: String,
    val settings: String,
    val pollInterval: String,
    val every5: String,
    val every10: String,
    val every15: String,
    val every30: String,
    val every60: String,
    val every120: String,
    val every300: String,
    val cpuAlertLbl: String,
    val memAlertLbl: String,
    // Process Kill & Alerts
    val kill: String,
    val killProcessTitle: String,
    val killConfirm: String,
    val sigtermDesc: String,
    val sigkillDesc: String,
    val killSuccess: String,
    val killError: String,
    val searchProcesses: String,
    val sortByCpu: String,
    val sortByMem: String,
    val globalCheck: String,
    val runProbe: String,
    val stopProbe: String,
    val probing: String,
    val probeTarget: String,
    val probeType: String,
    val probeSuccess: String,
    val nodes: String,
    val portNumber: String,
    val enterTarget: String,
    val testTelegram: String,
    val telegramSent: String,
    val telegramFailed: String,
    // Echoes Tools Suite
    val networkHub: String,
    val portsAndSockets: String,
    val listeningPorts: String,
    val activeConnections: String,
    val cloudflareDns: String,
    val saveToken: String,
    val changeToken: String,
    val addRecord: String,
    val addDnsRecord: String,
    val encryptedVault: String,
    val vaultHint: String,
    val masterPassword: String,
    val unlockVault: String,
    val notes: String,
    val addNote: String,
    val copy: String,
    val copied: String,
    val backup: String,
    val backupCopyHint: String,
    val devLab: String,
    val localWebServer: String,
    val startServer: String,
    val stopServer: String,
    val scan: String,
    val enterHostToScan: String,
    val inspect: String,
    val lookup: String,
    val start: String,
    val stop: String,
    val calculate: String,
    // Uptime Kuma Engine
    val uptimeMonitoring: String,
    val addMonitor: String,
    val noMonitorsHint: String,
    val navServers: String,
    val navUptime: String,
    val navNetwork: String,
    val navCloudflare: String,
    val navVault: String,
    val navTools: String
)

object Locales {
    val fa = Str(
        appName = "دیدبان",
        servers = "سرورها",
        noServers = "هنوز سروری اضافه نشده",
        noServersHint = "با دکمه‌ی زیر اولین سرورت را اضافه کن",
        addServer = "افزودن سرور",
        monitoringOn = "پایش روشن است",
        monitoringOff = "پایش خاموش است",
        langButton = "EN",
        manual = "دستی",
        sshInstall = "نصب با SSH",
        sshInstallHint = "آی‌پی و رمز root را بده؛ خودم ایجنت را نصب می‌کنم و رمز را پس می‌گیرم",
        name = "نام",
        host = "آدرس (IP یا دامنه)",
        port = "پورت",
        token = "توکن",
        useTls = "HTTPS (TLS)",
        fingerprint = "اثر انگشت سرتیفیکیت",
        fingerprintOptional = "اختیاری — خالی = اعتماد اولیه",
        pinCert = "قفل کردن این سرتیفیکیت",
        pinCertHint = "سرتیفیکیت هنوز قفل نشده — برای امنیت کامل آن را پین کن",
        sshUser = "کاربر SSH",
        sshPassword = "رمز SSH",
        install = "نصب",
        installing = "در حال نصب…",
        cancel = "انصراف",
        save = "ذخیره",
        close = "بستن",
        delete = "حذف",
        confirmDelete = "این سرور حذف شود؟",
        back = "بازگشت",
        overview = "نمای کلی",
        processes = "پروسه‌ها",
        events = "رویدادها",
        cpu = "پردازنده",
        memory = "حافظه",
        user = "کاربر",
        system = "سیستم",
        iowait = "انتظار I/O",
        steal = "دزدی (steal)",
        swap = "سواپ",
        disks = "دیسک‌ها",
        network = "شبکه",
        load = "لود",
        uptime = "آپتایم",
        cores = "هسته",
        noData = "داده‌ای نیست",
        connecting = "در حال اتصال…",
        error = "خطا",
        lastUpdate = "آخرین به‌روزرسانی",
        whatAteCpu = "چه چیزی منابع را خورد؟",
        spikeCpu = "اسپایک پردازنده",
        spikeMem = "اسپایک حافظه",
        topProcesses = "پروسه‌های مقصر",
        offline = "غیرقابل دسترس",
        serverSaved = "سرور ذخیره شد",
        installDone = "نصب کامل شد و سرور اضافه شد",
        installFailed = "نصب ناموفق",
        requiresRoot = "کاربر باید root باشد",
        available = "آزاد",
        used = "مصرف‌شده",
        yes = "بله",
        no = "خیر",
        eventProcessDown = "پروسه از دسترس خارج شد",
        eventProcessUp = "پروسه برگشت",
        eventDisk = "دیسک تقریباً پر",
        eventSteal = "دزدی CPU (steal)",
        eventAgentRestart = "ری‌استارت ایجنت",
        edit = "ویرایش",
        share = "اشتراک",
        latency = "زمان پاسخ",
        settings = "تنظیمات",
        pollInterval = "بازه پایش پس‌زمینه",
        every5 = "۵ ثانیه",
        every10 = "۱۰ ثانیه",
        every15 = "۱۵ ثانیه",
        every30 = "۳۰ ثانیه",
        every60 = "۱ دقیقه",
        every120 = "۲ دقیقه",
        every300 = "۵ دقیقه",
        cpuAlertLbl = "هشدار وقتی CPU بالاتر از (٪)",
        memAlertLbl = "هشدار وقتی رم بالاتر از (٪)",
        kill = "خاتمه",
        killProcessTitle = "خاتمه پروسه",
        killConfirm = "آیا از متوقف کردن این پروسه اطمینان دارید؟",
        sigtermDesc = "عادی (SIGTERM — توقف استاندارد)",
        sigkillDesc = "اجباری (SIGKILL — بستن فوری)",
        killSuccess = "دستور با موفقیت ارسال شد",
        killError = "خطا در خاتمه پروسه",
        searchProcesses = "جستجوی نام یا PID…",
        sortByCpu = "مرتب‌سازی: پردازنده",
        sortByMem = "مرتب‌سازی: رم",
        globalCheck = "تست جهانی",
        runProbe = "شروع تست",
        stopProbe = "توقف",
        probing = "در حال دریافت وضعیت از سرورهای جهانی…",
        probeTarget = "آدرس مقصد",
        probeType = "نوع تست",
        probeSuccess = "نود در دسترس",
        nodes = "نود",
        portNumber = "پورت (مثلاً 22 یا 443)",
        enterTarget = "آدرس یا IP را وارد کنید",
        testTelegram = "تست هشدار تلگرام",
        telegramSent = "پیام تست به تلگرام ارسال شد",
        telegramFailed = "خطا در ارسال تست تلگرام",
        networkHub = "ابزارهای شبکه",
        portsAndSockets = "پورت‌ها و سوکت‌ها",
        listeningPorts = "پورت‌های باز",
        activeConnections = "اتصالات فعال",
        cloudflareDns = "مدیریت Cloudflare DNS",
        saveToken = "ذخیره توکن",
        changeToken = "تغییر توکن",
        addRecord = "رکورد جدید",
        addDnsRecord = "افزودن رکورد DNS",
        encryptedVault = "گاوصندوق رمزنگاری‌شده",
        vaultHint = "رمز عبور اصلی برای گشایش گاوصندوق (رمزنگاری AES-256)",
        masterPassword = "رمز اصلی گاوصندوق",
        unlockVault = "بازگشایی قفل",
        notes = "یادداشت",
        addNote = "یادداشت جدید",
        copy = "کپی",
        copied = "در حافظه کپی شد",
        backup = "پشتیبان‌گیری",
        backupCopyHint = "متن رمزنگاری‌شده زیر را کپی کنید:",
        devLab = "جعبه‌ابزار توسعه",
        localWebServer = "وب‌سرور و اشتراک فایل",
        startServer = "روشن کردن سرور",
        stopServer = "خاموش کردن",
        scan = "اسکن",
        enterHostToScan = "یک آدرس برای اسکن وارد کنید",
        inspect = "بررسی",
        lookup = "استعلام",
        start = "شروع",
        stop = "توقف",
        calculate = "محاسبه",
        uptimeMonitoring = "پایش آپ‌تایم سرویس‌ها",
        addMonitor = "افزودن مانیتور",
        noMonitorsHint = "هنوز سایتی برای پایش پایداری اضافه نشده است",
        navServers = "سرورها",
        navUptime = "آپ‌تایم",
        navNetwork = "شبکه",
        navCloudflare = "کلودفلر",
        navVault = "گاوصندوق",
        navTools = "ابزارها"
    )

    val en = Str(
        appName = "Didban",
        servers = "Servers",
        noServers = "No servers yet",
        noServersHint = "Add your first server with the button below",
        addServer = "Add server",
        monitoringOn = "Monitoring is on",
        monitoringOff = "Monitoring is off",
        langButton = "فا",
        manual = "Manual",
        sshInstall = "Install via SSH",
        sshInstallHint = "Enter IP and root password; the agent is installed for you",
        name = "Name",
        host = "Host (IP or domain)",
        port = "Port",
        token = "Token",
        useTls = "HTTPS (TLS)",
        fingerprint = "Certificate fingerprint",
        fingerprintOptional = "optional — empty = trust on first use",
        pinCert = "Pin this certificate",
        pinCertHint = "Certificate not pinned yet — pin it for full security",
        sshUser = "SSH user",
        sshPassword = "SSH password",
        install = "Install",
        installing = "Installing…",
        cancel = "Cancel",
        save = "Save",
        close = "Close",
        delete = "Delete",
        confirmDelete = "Delete this server?",
        back = "Back",
        overview = "Overview",
        processes = "Processes",
        events = "Events",
        cpu = "CPU",
        memory = "Memory",
        user = "User",
        system = "System",
        iowait = "I/O wait",
        steal = "Steal",
        swap = "Swap",
        disks = "Disks",
        network = "Network",
        load = "Load",
        uptime = "Uptime",
        cores = "cores",
        noData = "No data",
        connecting = "Connecting…",
        error = "Error",
        lastUpdate = "Last update",
        whatAteCpu = "What ate my resources?",
        spikeCpu = "CPU spike",
        spikeMem = "Memory spike",
        topProcesses = "Top processes",
        offline = "Unreachable",
        serverSaved = "Server saved",
        installDone = "Installed and server added",
        installFailed = "Install failed",
        requiresRoot = "User must be root",
        available = "available",
        used = "used",
        yes = "Yes",
        no = "No",
        eventProcessDown = "Process died",
        eventProcessUp = "Process is back",
        eventDisk = "Disk almost full",
        eventSteal = "CPU steal",
        eventAgentRestart = "Agent restarted",
        edit = "Edit",
        share = "Share",
        latency = "Latency",
        settings = "Settings",
        pollInterval = "Background poll interval",
        every5 = "5s",
        every10 = "10s",
        every15 = "15s",
        every30 = "30 seconds",
        every60 = "1 minute",
        every120 = "2 minutes",
        every300 = "5 minutes",
        cpuAlertLbl = "Alert when CPU above (%)",
        memAlertLbl = "Alert when RAM above (%)",
        kill = "Kill",
        killProcessTitle = "Kill Process",
        killConfirm = "Are you sure you want to kill this process?",
        sigtermDesc = "Graceful (SIGTERM — clean shutdown)",
        sigkillDesc = "Force (SIGKILL — immediate stop)",
        killSuccess = "Kill signal sent successfully",
        killError = "Failed to send signal to process",
        searchProcesses = "Search by name or PID…",
        sortByCpu = "Sort: CPU",
        sortByMem = "Sort: RAM",
        globalCheck = "Check-Host",
        runProbe = "Run Check",
        stopProbe = "Stop",
        probing = "Collecting probe results from worldwide nodes…",
        probeTarget = "Target Host / IP",
        probeType = "Check Type",
        probeSuccess = "nodes reachable",
        nodes = "nodes",
        portNumber = "Port (e.g. 22 or 443)",
        enterTarget = "Enter target host or IP",
        testTelegram = "Test Telegram Alert",
        telegramSent = "Test alert sent to Telegram",
        telegramFailed = "Failed to send Telegram test",
        networkHub = "Network Hub",
        portsAndSockets = "Ports & Sockets",
        listeningPorts = "Listening Ports",
        activeConnections = "Active Connections",
        cloudflareDns = "Cloudflare DNS",
        saveToken = "Save Token",
        changeToken = "Change Token",
        addRecord = "Add Record",
        addDnsRecord = "Add DNS Record",
        encryptedVault = "Encrypted Vault",
        vaultHint = "Enter master password to unlock vault (AES-256)",
        masterPassword = "Master Password",
        unlockVault = "Unlock Vault",
        notes = "Notes",
        addNote = "Add Note",
        copy = "Copy",
        copied = "Copied to clipboard",
        backup = "Backup",
        backupCopyHint = "Copy the encrypted backup below:",
        devLab = "Developer Lab",
        localWebServer = "Local Web Server",
        startServer = "Start Server",
        stopServer = "Stop Server",
        scan = "Scan",
        enterHostToScan = "Enter host or IP to scan",
        inspect = "Inspect",
        lookup = "Lookup",
        start = "Start",
        stop = "Stop",
        calculate = "Calculate",
        uptimeMonitoring = "Uptime Monitoring",
        addMonitor = "Add Monitor",
        noMonitorsHint = "No uptime monitors configured yet",
        navServers = "Servers",
        navUptime = "Uptime",
        navNetwork = "Network",
        navCloudflare = "Cloudflare",
        navVault = "Vault",
        navTools = "Dev Lab"
    )
}
