package org.didban.monitor

/** UI strings in both languages — the whole app reads from an instance of this. */
class Str(
    val appName: String,
    val appSubtitle: String,
    val servers: String,
    val noServers: String,
    val noServersHint: String,
    val addServer: String,
    val monitoringOn: String,
    val monitoringOff: String,
    val langButton: String,
    val manual: String,
    val sshInstall: String,
    val sshInstallHint: String,
    val name: String,
    val host: String,
    val port: String,
    val token: String,
    val useTls: String,
    val fingerprint: String,
    val fingerprintOptional: String,
    val pinCert: String,
    val pinCertHint: String,
    val sshUser: String,
    val sshPassword: String,
    val install: String,
    val installing: String,
    val cancel: String,
    val save: String,
    val close: String,
    val delete: String,
    val confirmDelete: String,
    val back: String,
    val overview: String,
    val processes: String,
    val events: String,
    val cpu: String,
    val memory: String,
    val user: String,
    val system: String,
    val iowait: String,
    val steal: String,
    val swap: String,
    val disks: String,
    val network: String,
    val load: String,
    val uptime: String,
    val cores: String,
    val noData: String,
    val connecting: String,
    val error: String,
    val lastUpdate: String,
    val whatAteCpu: String,
    val spikeCpu: String,
    val spikeMem: String,
    val topProcesses: String,
    val offline: String,
    val online: String,
    val serverSaved: String,
    val installDone: String,
    val installFailed: String,
    val requiresRoot: String,
    val available: String,
    val used: String,
    val yes: String,
    val no: String,
    val eventProcessDown: String,
    val eventProcessUp: String,
    val eventDisk: String,
    val eventSteal: String,
    val eventAgentRestart: String,
    val edit: String,
    val share: String,
    val latency: String,
    val settings: String,
    val pollInterval: String,
    val every5: String,
    val every10: String,
    val every15: String,
    val every30: String,
    val every60: String,
    val every120: String,
    val every300: String,
    val cpuAlertLbl: String,
    val memAlertLbl: String,
    // Process Kill & Alerts
    val kill: String,
    val killProcessTitle: String,
    val killConfirm: String,
    val sigtermDesc: String,
    val sigkillDesc: String,
    val killSuccess: String,
    val killError: String,
    val searchProcesses: String,
    val sortByCpu: String,
    val sortByMem: String,
    val globalCheck: String,
    val runProbe: String,
    val stopProbe: String,
    val probing: String,
    val probeTarget: String,
    val probeType: String,
    val probeSuccess: String,
    val nodes: String,
    val portNumber: String,
    val enterTarget: String,
    val testTelegram: String,
    val telegramSent: String,
    val telegramFailed: String,
    // Dual-Node Tunnels
    val navTunnels: String,
    val tunnelsHub: String,
    val guideTunnels: String,
    val addTunnel: String,
    val editTunnel: String,
    val deleteTunnel: String,
    val tunnelCore: String,
    val iranNode: String,
    val foreignNode: String,
    val iranListenPort: String,
    val foreignTargetPort: String,
    val coreCommPort: String,
    val tunnelTransport: String,
    val secretToken: String,
    val generateToken: String,
    val copyIranCommand: String,
    val copyForeignCommand: String,
    val testTunnel: String,
    val viewConfigs: String,
    // Echoes Tools Suite
    val networkHub: String,
    val portsAndSockets: String,
    val listeningPorts: String,
    val activeConnections: String,
    val cloudflareDns: String,
    val saveToken: String,
    val changeToken: String,
    val addRecord: String,
    val addDnsRecord: String,
    val encryptedVault: String,
    val vaultHint: String,
    val masterPassword: String,
    val unlockVault: String,
    val notes: String,
    val addNote: String,
    val copy: String,
    val copied: String,
    val backup: String,
    val backupCopyHint: String,
    val devLab: String,
    val localWebServer: String,
    val startServer: String,
    val stopServer: String,
    val scan: String,
    val enterHostToScan: String,
    val inspect: String,
    val lookup: String,
    val start: String,
    val stop: String,
    val calculate: String,
    // Uptime Kuma Engine
    val uptimeMonitoring: String,
    val addMonitor: String,
    val noMonitorsHint: String,
    val navServers: String,
    val navUptime: String,
    val navNetwork: String,
    val navCloudflare: String,
    val navVault: String,
    val navTools: String,
    // Descriptions & Guides
    val tipHeader: String,
    val guideCensorship: String,
    val guideVault: String,
    val guideUptime: String,
    val guideDocker: String,
    val guideSockets: String,
    val guideSpikes: String,
    val guideDevLab: String,
    val guideCloudflare: String,
    // Nightwatch UI
    val monitorHintOn: String,
    val monitorHintOff: String,
    val startShort: String,
    val stopShort: String,
    val quickConnectGuide: String,
    val quickConnectBody: String,
    val cmdCopied: String,
    val smartPaste: String,
    val clipboardParsed: String,
    val clipboardNotFound: String,
    val testConnection: String,
    val testOk: String,
    val testFail: String,
    val lblCpuUse: String,
    val lblRamUse: String,
    val lblDiskFree: String,
    val lblUptime: String,
    val lblNetLive: String,
    val lblLoad1m: String,
    val lblLatency: String,
    val lblUptimeServer: String,
    val lblCharts24h: String,
    val lblCollecting: String,
    val liveProcessWatch: String,
    val dockerContainersLbl: String,
    val spikeDetective: String,
    val processManager: String,
    val noSpikes24h: String,
    val dockerNotRunning: String,
    val containerRestartedTpl: String,
    val containerStoppedTpl: String,
    val restartLbl: String,
    val errorShort: String,
    val monitorsTotalLbl: String,
    val upLbl: String,
    val withDowntimeLbl: String,
    val noMonitorsTitle: String,
    val noMonitorsBody: String,
    val incidentHistory: String,
    val noIncidents: String,
    val incidentTpl: String,
    val resumeWatch: String,
    val pauseWatch: String,
    val recheckNow: String,
    val statusUpdated: String,
    val deleteMonitorTitle: String,
    val confirmDeleteMonitorTpl: String,
    val monitorNameLbl: String,
    val protocolTypeLbl: String,
    val monitorPortLbl: String,
    val monitorKeywordLbl: String,
    val testBeforeSave: String,
    val probeOkTpl: String,
    val probeFail: String,
    val editMonitorTitle: String
)

object Locales {
    val fa = Str(
        appName = "دیدبان",
        appSubtitle = "مرکز فرماندهی و پایش سرور",
        servers = "سرورها",
        noServers = "هنوز سروری اضافه نشده",
        noServersHint = "با دکمه‌ی زیر اولین سرورتان را متصل کنید",
        addServer = "افزودن سرور جدید",
        monitoringOn = "پایش زنده فعال است",
        monitoringOff = "پایش پس‌زمینه خاموش است",
        langButton = "EN",
        manual = "اتصال دستی",
        sshInstall = "نصب خودکار با SSH",
        sshInstallHint = "آی‌پی و رمز root سرور را وارد کنید تا ایجنت Go به‌صورت خودکار و ایمن نصب شود",
        name = "نام دلخواه سرور",
        host = "آدرس (IP یا دامنه)",
        port = "پورت ایجنت",
        token = "توکن احراز هویت",
        useTls = "اتصال امن HTTPS (TLS)",
        fingerprint = "اثر انگشت سرتیفیکیت (Fingerprint)",
        fingerprintOptional = "اختیاری — خالی = اعتماد اولیه",
        pinCert = "قفل کردن این سرتیفیکیت",
        pinCertHint = "سرتیفیکیت هنوز قفل نشده — برای امنیت کامل آن را پین کنید",
        sshUser = "کاربر SSH (مثلا root)",
        sshPassword = "رمز عبور SSH",
        install = "نصب و اتصال",
        installing = "در حال نصب خودکار ایجنت…",
        cancel = "انصراف",
        save = "ذخیره تغییرات",
        close = "بستن",
        delete = "حذف سرور",
        confirmDelete = "آیا از حذف این سرور اطمینان دارید؟",
        back = "بازگشت",
        overview = "نمای کلی",
        processes = "پروسه‌ها",
        events = "رویدادها",
        cpu = "پردازنده (CPU)",
        memory = "حافظه (RAM)",
        user = "کاربر",
        system = "سیستم",
        iowait = "انتظار دیسک (I/O)",
        steal = "دزدی هسته (Steal)",
        swap = "حافظه مجازی (Swap)",
        disks = "فضای دیسک‌ها",
        network = "ترافیک شبکه",
        load = "میانگین لود",
        uptime = "مدت زمان روشن بودن",
        cores = "هسته",
        noData = "داده‌ای برای نمایش موجود نیست",
        connecting = "در حال اتصال به سرور…",
        error = "خطای ارتباط",
        lastUpdate = "آخرین به‌روزرسانی",
        whatAteCpu = "چه چیزی منابع سرور را خورد؟",
        spikeCpu = "اسپایک شدید پردازنده",
        spikeMem = "اسپایک شدید رم",
        topProcesses = "پروسه‌های مقصر مصرف بالا",
        offline = "غیرقابل دسترس",
        online = "فعال و آنلاین",
        serverSaved = "مشخصات سرور ذخیره شد",
        installDone = "ایجنت با موفقیت نصب شد و سرور متصل گردید",
        installFailed = "نصب ناموفق بود",
        requiresRoot = "کاربر باید دسترسی root داشته باشد",
        available = "فضای آزاد",
        used = "مصرف‌شده",
        yes = "بله",
        no = "خیر",
        eventProcessDown = "پروسه متوقف شد",
        eventProcessUp = "پروسه مجدداً بالا آمد",
        eventDisk = "دیسک نزدیک به پر شدن",
        eventSteal = "افزایش Steal پردازنده",
        eventAgentRestart = "ایجنت ری‌استارت شد",
        edit = "ویرایش",
        share = "اشتراک‌گذاری لاگ",
        latency = "زمان پاسخ (Latency)",
        settings = "تنظیمات پایش",
        pollInterval = "بازه بررسی پس‌زمینه",
        every5 = "۵ ثانیه",
        every10 = "۱۰ ثانیه",
        every15 = "۱۵ ثانیه",
        every30 = "۳۰ ثانیه",
        every60 = "۱ دقیقه",
        every120 = "۲ دقیقه",
        every300 = "۵ دقیقه",
        cpuAlertLbl = "آستانه هشدار CPU بالاتر از (٪)",
        memAlertLbl = "آستانه هشدار RAM بالاتر از (٪)",
        kill = "متوقف‌سازی",
        killProcessTitle = "بستن و خاتمه دادن به پروسه",
        killConfirm = "آیا مطمئن هستید که می‌خواهید این پروسه را متوقف کنید؟",
        sigtermDesc = "توقف استاندارد (SIGTERM — اجازه ذخیره وضعیت)",
        sigkillDesc = "بستن فوری و اجباری (SIGKILL — قطع بدون درنگ)",
        killSuccess = "دستور بستن پروسه با موفقیت ارسال شد",
        killError = "خطا در متوقف کردن پروسه",
        searchProcesses = "جستجوی نام پروسه یا PID…",
        sortByCpu = "مرتب‌سازی بر اساس پردازنده",
        sortByMem = "مرتب‌سازی بر اساس رم",
        globalCheck = "تست دسترسی جهانی",
        runProbe = "شروع تست",
        stopProbe = "توقف تست",
        probing = "در حال دریافت وضعیت از سرورهای جهانی…",
        probeTarget = "آدرس سرور یا دامنه مقصد",
        probeType = "نوع تست اتصال",
        probeSuccess = "نود در دسترس است",
        nodes = "نود جهانی",
        portNumber = "شماره پورت (مثلا 22 یا 443)",
        enterTarget = "آدرس IP یا دامنه مورد نظر را وارد کنید",
        testTelegram = "تست هشدار تلگرام",
        telegramSent = "پیام تست با موفقیت به تلگرام ارسال شد",
        telegramFailed = "ارسال هشدار به تلگرام ناموفق بود",
        // Dual-Node Tunnels
        navTunnels = "تانل‌ها",
        tunnelsHub = "مرکز تانل بین دو سرور",
        guideTunnels = "مدیریت و برقراری تانل‌های معکوس، سوکت خام، پینگ ICMP و IP Spoofing (شامل BackPack 🎒، Paqet، Narnia، Spoof Tunnel، Backhaul، Rathole، GOST، Chisel، FRP و IPTables) بین سرور ایران و خارج همراه با استقرار خودکار ۱-کلیکه مانند پنل Smite.",
        addTunnel = "ساخت تانل جدید",
        editTunnel = "ویرایش مشخصات تانل",
        deleteTunnel = "حذف تانل",
        tunnelCore = "هسته تانل",
        iranNode = "سرور ایران (پل ارتباطی / Relay)",
        foreignNode = "سرور خارج (مقصد / Upstream)",
        iranListenPort = "پورت ورودی ایران (Listen)",
        foreignTargetPort = "پورت مقصد خارج (Target)",
        coreCommPort = "پورت ارتباطی تانل (Core Port)",
        tunnelTransport = "پروتکل انتقال ترافیک",
        secretToken = "توکن اختصاصی امنیتی",
        generateToken = "تولید توکن قوی",
        copyIranCommand = "کپی دستور سرور ایران",
        copyForeignCommand = "کپی دستور سرور خارج",
        testTunnel = "تست پایداری و پینگ",
        viewConfigs = "کانفیگ‌ها و داکر",
        // Echoes Tools Suite
        networkHub = "ابزارهای شبکه و عیب‌یابی",
        portsAndSockets = "پورت‌ها و سوکت‌ها",
        listeningPorts = "پورت‌های باز",
        activeConnections = "اتصالات فعال",
        cloudflareDns = "مدیریت DNS کلودفلر",
        saveToken = "ذخیره توکن API",
        changeToken = "تغییر توکن",
        addRecord = "رکورد جدید",
        addDnsRecord = "افزودن رکورد جدید DNS",
        encryptedVault = "گاوصندوق امن محرمانه",
        vaultHint = "رمز عبور اصلی برای گشایش گاوصندوق (رمزنگاری نظامی AES-256)",
        masterPassword = "رمز عبور اصلی گاوصندوق",
        unlockVault = "بازگشایی قفل گاوصندوق",
        notes = "یادداشت و کلید محرمانه",
        addNote = "یادداشت / کلید جدید",
        copy = "کپی در حافظه",
        copied = "با موفقیت کپی شد!",
        backup = "پشتیبان‌گیری رمزنگاری‌شده",
        backupCopyHint = "رشته رمزنگاری‌شده زیر شامل سرورها و کلیدهای شماست:",
        devLab = "جعبه‌ابزار کاربردی",
        localWebServer = "وب‌سرور و اشتراک فایل با QR",
        startServer = "روشن کردن وب‌سرور",
        stopServer = "خاموش کردن",
        scan = "شروع اسکن پورت‌ها",
        enterHostToScan = "یک آدرس برای اسکن پورت‌ها وارد کنید",
        inspect = "بررسی گواهی SSL",
        lookup = "استعلام موقعیت IP",
        start = "شروع پینگ",
        stop = "توقف",
        calculate = "محاسبه ساب‌نت",
        uptimeMonitoring = "پایش پایداری و سلامت سایت‌ها",
        addMonitor = "افزودن مانیتور جدید",
        noMonitorsHint = "هنوز سایتی برای پایش پایداری و آپ‌تایم ثبت نشده است",
        navServers = "سرورها",
        navUptime = "آپ‌تایم",
        navNetwork = "شبکه",
        navCloudflare = "کلودفلر",
        navVault = "گاوصندوق",
        navTools = "ابزارها",
        tipHeader = "💡 نکته: اطلاعات پردازنده، رم و دیسک هر چند ثانیه به‌صورت زنده دریافت می‌شوند.",
        guideCensorship = "این ابزار هوشمند، اختلالات اینترنت و فیلترینگ را تفکیک می‌کند: آیا سرور فیلتر شده، پکت‌های TCP RST توسط فیلترینگ تزریق می‌شوند، یا پروتکل TLS/SNI قطع شده است.",
        guideVault = "گاوصندوق امن محلی برای ذخیره کلیدهای SSH، رمزها، توکن‌ها و کانفیگ‌ها با رمزنگاری نظامی AES-256 (داده‌ها فقط روی گوشی شما ذخیره می‌شوند و به هیچ سروری ارسال نمی‌گردند).",
        guideUptime = "پایش ۲۴ ساعته پایداری سایت‌ها، وب‌سرویس‌ها، پورت دیتابیس‌ها و گواهی SSL با نوارهای ضربان قلب ۳۰ تایی (مشابه Uptime Kuma) و هشدار قطعی آنی.",
        guideDocker = "مشاهده و کنترل تمام کانتینرهای فعال و متوقف Docker روی سرور، بدون نیاز به خط فرمان با امکان ری‌استارت یا توقف با یک کلیک.",
        guideSockets = "مشاهده زنده تمام پورت‌های در حال شنود (Listening) و ارتباطات فعال شبکه همراه با نام پروسه و شماره PID.",
        guideSpikes = "کارآگاه اسپایک: هر زمان مصرف پردازنده یا رم سرور به‌طور ناگهانی بالا برود، دیدبان پروسه‌های مقصر را به همراه جزئیات کامل ذخیره می‌کند.",
        guideDevLab = "مجموعه ابزارهای دم‌دستی برای برنامه‌نویسان و ادمین‌ها: فرمت JSON، دیکودر توکن‌های JWT، محاسبه‌گر ساب‌نت شبکه، و تولیدکننده پسورد و UUID.",
        guideCloudflare = "مدیریت مستقیم رکوردهای دامنه (A, AAAA, CNAME) و تغییر وضعیت پروکسی ابری بدون نیاز به ورود به داشبورد سنگین کلودفلر.",
        // Nightwatch UI
        monitorHintOn = "پایش خودکار پس‌زمینه فعال است",
        monitorHintOff = "پایش پس‌زمینه متوقف است",
        startShort = "شروع",
        stopShort = "توقف",
        quickConnectGuide = "راهنمای اتصال سریع سرور",
        quickConnectBody = "برای اتصال سرور لینوکس (Ubuntu, Debian, CentOS, AlmaLinux) دستور زیر را در ترمینال سرور اجرا کنید:",
        cmdCopied = "دستور نصب کپی شد!",
        smartPaste = "الصاق خودکار مشخصات از کلیپ‌بورد",
        clipboardParsed = "اطلاعات از کلیپ‌بورد شناسایی شد!",
        clipboardNotFound = "مشخصات معتبری در کلیپ‌بورد یافت نشد",
        testConnection = "تست اتصال",
        testOk = "اتصال موفق!",
        testFail = "خطا در اتصال",
        lblCpuUse = "مصرف پردازنده",
        lblRamUse = "حافظه رم",
        lblDiskFree = "فضای آزاد دیسک",
        lblUptime = "آپ‌تایم سیستم",
        lblNetLive = "ترافیک زنده شبکه",
        lblLoad1m = "لود پردازنده (Load 1m)",
        lblLatency = "زمان پاسخ",
        lblUptimeServer = "آپتایم سرور",
        lblCharts24h = "نمودار تغییرات ۲۴ ساعته پردازنده و رم",
        lblCollecting = "در حال جمع‌آوری تاریخچه…",
        liveProcessWatch = "پایش زنده و رصد سریع پروسه‌ها",
        dockerContainersLbl = "کانتینرهای داکر",
        spikeDetective = "کارآگاه اسپایک",
        processManager = "مدیریت پروسه‌ها",
        noSpikes24h = "هیچ اسپایکی در ۲۴ ساعت گذشته ثبت نشده است",
        dockerNotRunning = "سرویس Docker روی این سرور در حال اجرا نیست",
        containerRestartedTpl = "کانتینر %s ری‌استارت شد",
        containerStoppedTpl = "کانتینر %s متوقف شد",
        restartLbl = "ری‌استارت",
        errorShort = "خطا",
        monitorsTotalLbl = "کل مانیتورها",
        upLbl = "آنلاین",
        withDowntimeLbl = "دارای قطعی",
        noMonitorsTitle = "هنوز مانیتوری ثبت نشده است",
        noMonitorsBody = "با افزودن اولین مانیتور، وضعیت در دسترس بودن سرویس‌های شما به‌صورت خودکار و شبانه‌روزی بررسی می‌شود.",
        incidentHistory = "تاریخچه حوادث و قطعی‌ها",
        noIncidents = "هیچ حادثه قطعی برای این سرویس ثبت نشده است",
        incidentTpl = "%1\$s — قطعی به مدت %2\$d ثانیه (%3\$s)",
        resumeWatch = "ادامه پایش",
        pauseWatch = "توقف موقت",
        recheckNow = "بررسی مجدد",
        statusUpdated = "وضعیت به‌روزرسانی شد",
        deleteMonitorTitle = "حذف مانیتور",
        confirmDeleteMonitorTpl = "آیا از حذف مانیتور «%s» اطمینان دارید؟",
        monitorNameLbl = "نام دلخواه مانیتور",
        protocolTypeLbl = "نوع پروتکل",
        monitorPortLbl = "شماره پورت (مثلاً 443, 80, 5432, 3306, 6379, 22)",
        monitorKeywordLbl = "کلمه کلیدی مورد انتظار (مثلاً ok یا status)",
        testBeforeSave = "تست اتصال قبل از ذخیره",
        probeOkTpl = "پاسخ دریافت شد! (زمان پاسخ: %d میلی‌ثانیه)",
        probeFail = "پاسخ دریافت نشد یا خطایی رخ داد",
        editMonitorTitle = "ویرایش مانیتور"
    )

    val en = Str(
        appName = "Didban",
        appSubtitle = "DevOps Command Center",
        servers = "Servers",
        noServers = "No servers added yet",
        noServersHint = "Add your first server with the button below",
        addServer = "Add Server",
        monitoringOn = "Live monitoring is active",
        monitoringOff = "Background polling is paused",
        langButton = "فا",
        manual = "Manual Setup",
        sshInstall = "1-Click SSH Install",
        sshInstallHint = "Enter server IP and root password to automatically install the lightweight Go agent",
        name = "Server Label",
        host = "Host (IP or Domain)",
        port = "Agent Port",
        token = "Auth Token",
        useTls = "HTTPS (TLS Encryption)",
        fingerprint = "Certificate Fingerprint",
        fingerprintOptional = "optional — empty = trust on first use",
        pinCert = "Pin this certificate",
        pinCertHint = "Certificate not pinned yet — pin it for full security",
        sshUser = "SSH User (e.g. root)",
        sshPassword = "SSH Password",
        install = "Install & Connect",
        installing = "Installing agent…",
        cancel = "Cancel",
        save = "Save Changes",
        close = "Close",
        delete = "Delete Server",
        confirmDelete = "Are you sure you want to delete this server?",
        back = "Back",
        overview = "Overview",
        processes = "Processes",
        events = "Spike Events",
        cpu = "Processor (CPU)",
        memory = "Memory (RAM)",
        user = "User",
        system = "System",
        iowait = "I/O Wait",
        steal = "CPU Steal",
        swap = "Virtual Swap",
        disks = "Disk Volumes",
        network = "Network Traffic",
        load = "Load Average",
        uptime = "System Uptime",
        cores = "cores",
        noData = "No data available",
        connecting = "Connecting to server…",
        error = "Connection Error",
        lastUpdate = "Last update",
        whatAteCpu = "What ate your server resources?",
        spikeCpu = "CPU Spike",
        spikeMem = "Memory Spike",
        topProcesses = "Culprit Processes",
        offline = "Unreachable",
        online = "Online & Healthy",
        serverSaved = "Server saved successfully",
        installDone = "Agent installed and server connected!",
        installFailed = "Installation failed",
        requiresRoot = "User must be root",
        available = "available",
        used = "used",
        yes = "Yes",
        no = "No",
        eventProcessDown = "Process died",
        eventProcessUp = "Process is back",
        eventDisk = "Disk almost full",
        eventSteal = "CPU steal alert",
        eventAgentRestart = "Agent restarted",
        edit = "Edit",
        share = "Share Event Log",
        latency = "Latency",
        settings = "Monitoring Settings",
        pollInterval = "Background poll interval",
        every5 = "5 seconds",
        every10 = "10 seconds",
        every15 = "15 seconds",
        every30 = "30 seconds",
        every60 = "1 minute",
        every120 = "2 minutes",
        every300 = "5 minutes",
        cpuAlertLbl = "Alert threshold: CPU above (%)",
        memAlertLbl = "Alert threshold: RAM above (%)",
        kill = "Kill Process",
        killProcessTitle = "Terminate Process",
        killConfirm = "Are you sure you want to terminate this process?",
        sigtermDesc = "Graceful (SIGTERM — allows clean state saving)",
        sigkillDesc = "Force Kill (SIGKILL — terminates immediately)",
        killSuccess = "Kill signal sent successfully",
        killError = "Failed to send signal to process",
        searchProcesses = "Search by process name or PID…",
        sortByCpu = "Sort by CPU Usage",
        sortByMem = "Sort by RAM Usage",
        globalCheck = "Global Reachability",
        runProbe = "Run Check",
        stopProbe = "Stop Check",
        probing = "Probing nodes worldwide…",
        probeTarget = "Target Host or Domain",
        probeType = "Check Type",
        probeSuccess = "nodes reachable",
        nodes = "nodes",
        portNumber = "Port (e.g. 22 or 443)",
        enterTarget = "Enter target host or IP",
        testTelegram = "Test Telegram Alert",
        telegramSent = "Test alert sent to Telegram",
        telegramFailed = "Failed to send Telegram test",
        // Dual-Node Tunnels
        navTunnels = "Tunnels",
        tunnelsHub = "Dual-Node Tunnel Hub",
        guideTunnels = "Manage high-performance reverse, raw-socket, ICMP ping, and IP spoofing tunnels (BackPack 🎒, Paqet, Narnia, Spoof Tunnel, Backhaul, Rathole, GOST, Chisel, FRP, IPTables) with Smite-style zero-touch auto-sync.",
        addTunnel = "New Tunnel",
        editTunnel = "Edit Tunnel",
        deleteTunnel = "Delete Tunnel",
        tunnelCore = "Tunnel Core",
        iranNode = "Iran Node (Relay / Bridge)",
        foreignNode = "Foreign Server (Upstream / Target)",
        iranListenPort = "Iran Listen Port",
        foreignTargetPort = "Foreign Target Port",
        coreCommPort = "Core Tunnel Port",
        tunnelTransport = "Transport Protocol",
        secretToken = "Security Token",
        generateToken = "Generate Token",
        copyIranCommand = "Copy Iran Command",
        copyForeignCommand = "Copy Foreign Command",
        testTunnel = "Test Tunnel Latency",
        viewConfigs = "Configs & Docker",
        // Echoes Tools Suite
        networkHub = "Network & Diagnostic Hub",
        portsAndSockets = "Ports & Sockets",
        listeningPorts = "Listening Ports",
        activeConnections = "Active Connections",
        cloudflareDns = "Cloudflare DNS Manager",
        saveToken = "Save API Token",
        changeToken = "Change Token",
        addRecord = "New Record",
        addDnsRecord = "Add DNS Record",
        encryptedVault = "Encrypted Secrets Vault",
        vaultHint = "Master password for AES-256 vault encryption",
        masterPassword = "Vault Master Password",
        unlockVault = "Unlock Vault",
        notes = "Confidential Secrets",
        addNote = "New Secret / Note",
        copy = "Copy",
        copied = "Copied to clipboard!",
        backup = "Encrypted Backup",
        backupCopyHint = "Copy the encrypted backup string below:",
        devLab = "Developer Lab",
        localWebServer = "Local Web Server & QR Share",
        startServer = "Start Web Server",
        stopServer = "Stop Server",
        scan = "Scan Common Ports",
        enterHostToScan = "Enter host or IP to scan",
        inspect = "Inspect SSL Certificate",
        lookup = "Lookup IP Geo Data",
        start = "Start Ping",
        stop = "Stop",
        calculate = "Calculate Subnet",
        uptimeMonitoring = "Uptime & Service Health",
        addMonitor = "Add New Monitor",
        noMonitorsHint = "No uptime monitors configured yet",
        navServers = "Servers",
        navUptime = "Uptime",
        navNetwork = "Network",
        navCloudflare = "Cloudflare",
        navVault = "Vault",
        navTools = "Tools",
        tipHeader = "💡 Tip: CPU, RAM, and Disk metrics are refreshed in real-time from the Go agent.",
        guideCensorship = "Diagnoses network interference: distinguishes between routing blackholes, DPI TCP RST packet injections, and TLS/SNI handshake filtering.",
        guideVault = "A zero-knowledge AES-256 encrypted local vault to keep your SSH private keys, API credentials, and secrets safe right on your phone.",
        guideUptime = "24/7 service availability monitoring (Uptime Kuma style) with 30-bar heartbeats and instant multi-channel downtime alerts.",
        guideDocker = "Live monitoring and remote 1-click restart/stop for all Docker containers directly through the native unix socket.",
        guideSockets = "Live inspection of listening ports and active socket connections matched to PIDs and process names.",
        guideSpikes = "Spike Forensics: Automatically records the culprit processes behind any CPU/memory spike even while your phone is off.",
        guideDevLab = "Everyday developer utilities: JSON formatting, JWT token decoder, CIDR subnet calculator, and secure password/UUID generators.",
        guideCloudflare = "Quickly manage Cloudflare DNS records (A, AAAA, CNAME) and toggle proxy status without the bulky web console.",
        // Nightwatch UI
        monitorHintOn = "Background auto-polling is active",
        monitorHintOff = "Background polling is stopped",
        startShort = "Start",
        stopShort = "Stop",
        quickConnectGuide = "Quick server onboarding",
        quickConnectBody = "Run this one-liner on any Linux server (Ubuntu, Debian, CentOS, AlmaLinux) to connect it:",
        cmdCopied = "Install command copied!",
        smartPaste = "Smart-paste credentials from clipboard",
        clipboardParsed = "Credentials detected in clipboard!",
        clipboardNotFound = "No valid credentials found in clipboard",
        testConnection = "Test Connection",
        testOk = "Connection successful!",
        testFail = "Connection failed",
        lblCpuUse = "CPU usage",
        lblRamUse = "Memory",
        lblDiskFree = "Disk free",
        lblUptime = "System uptime",
        lblNetLive = "Live network traffic",
        lblLoad1m = "CPU load (1m)",
        lblLatency = "Latency",
        lblUptimeServer = "Server uptime",
        lblCharts24h = "24-hour CPU & memory telemetry",
        lblCollecting = "Collecting history…",
        liveProcessWatch = "Live process watch",
        dockerContainersLbl = "Docker containers",
        spikeDetective = "Spike detective",
        processManager = "Process manager",
        noSpikes24h = "No spikes recorded in the last 24 hours",
        dockerNotRunning = "Docker is not running on this server",
        containerRestartedTpl = "Container %s restarted",
        containerStoppedTpl = "Container %s stopped",
        restartLbl = "Restart",
        errorShort = "Error",
        monitorsTotalLbl = "Monitors",
        upLbl = "Up",
        withDowntimeLbl = "Down",
        noMonitorsTitle = "No monitors yet",
        noMonitorsBody = "Add your first monitor and Didban will keep watch over your services around the clock.",
        incidentHistory = "Incident history",
        noIncidents = "No incidents recorded for this service",
        incidentTpl = "%1\$s — down for %2\$d s (%3\$s)",
        resumeWatch = "Resume",
        pauseWatch = "Pause",
        recheckNow = "Recheck",
        statusUpdated = "Status updated",
        deleteMonitorTitle = "Delete monitor",
        confirmDeleteMonitorTpl = "Delete monitor “%s”?",
        monitorNameLbl = "Monitor label",
        protocolTypeLbl = "Protocol type",
        monitorPortLbl = "Port (e.g. 443, 80, 5432, 3306, 6379, 22)",
        monitorKeywordLbl = "Expected keyword (e.g. ok or status)",
        testBeforeSave = "Test before saving",
        probeOkTpl = "Response received! (latency: %d ms)",
        probeFail = "No response or an error occurred",
        editMonitorTitle = "Edit monitor"
    )
}
